import type {AgendaRepository} from '../repositories/AgendaRepository';
import {RepositoryError} from '../repositories/AgendaRepository';
import type {AgendaStore} from '../stores/AgendaStore';
import type {AuthManager} from '../auth/AuthManager';
export class SyncEngine {
 private readonly generation:number;private readonly identity:string|null;
 private running:Promise<void>|null=null;private stopListeners:(()=>void)|null=null;
 constructor(private store:AgendaStore,private remote:AgendaRepository,private auth:AuthManager,private random= Math.random){this.generation=auth.generation;this.identity=auth.identity;}
 stop(){this.stopListeners?.();this.stopListeners=null}
 start(target:Window=window){this.stop();const run=()=>{void this.sync()};target.addEventListener('online',run);target.addEventListener('focus',run);const timer=setInterval(run,15000);const unsubscribe=this.auth.onInvalidate(()=>this.stop());this.stopListeners=()=>{target.removeEventListener('online',run);target.removeEventListener('focus',run);clearInterval(timer);unsubscribe()};run();return ()=>this.stop()}
 sync(){if(this.running)return this.running;this.running=this.run().finally(()=>{this.running=null});return this.running}
 private async run(){const g=this.generation;const valid=()=>this.auth.valid(g)&&this.auth.identity===this.identity;if(!valid())return;const s=this.store;let issue:RepositoryError['code']|null=null;s.status='syncing';s.emit();try{let cursor=s.cursor,reset=false;for(let pages=0;pages<10000;pages++){let page;try{page=await this.remote.fetchChanges(cursor)}catch(e){if(e instanceof RepositoryError&&e.code==='tokenExpired'&&!reset){cursor=undefined;reset=true;continue}throw e}if(!valid())return;await s.remote(page.entities,page.cursor,undefined,page.quarantine);if(!valid())return;if(!page.moreComing)break;if(page.cursor===cursor)throw Error('CURSOR_STALLED');cursor=page.cursor;}
 const blocked=new Set<string>();for(const op of [...s.outbox]){if(!valid())return;if(blocked.has(op.entityID))continue;if(op.status==='permanentFailure'||op.nextAttemptAt>Date.now()){blocked.add(op.entityID);continue}await s.markOperation(op.operationID,{status:'sending'});if(!valid())return;try{const saved=await this.remote.save(op.payload,op.operationID);if(!valid())return;await s.remote([saved],undefined,op.operationID)}catch(error){if(!valid())return;const e=error instanceof RepositoryError?error:new RepositoryError('unknown');if(e.code==='authentication'){s.syncIssueCause=e.code;s.error=e.code;s.emit();this.auth.expire();return}const permanent=['invalidRecord','permission','zoneMissing'].includes(e.code);if(!issue||permanent)issue=e.code;const delay=Math.max(e.retryAfter,Math.min(300000,1000*2**Math.min(op.attempts,8))*(.75+this.random()*.5));await s.markOperation(op.operationID,{status:permanent?'permanentFailure':e.code==='conflict'?'conflict':'retry',attempts:op.attempts+1,nextAttemptAt:Date.now()+delay});blocked.add(op.entityID)}}if(valid()){s.status=s.outbox.length?'pending':'ready';s.syncIssueCause=issue;s.error=issue??'';s.lastSync=new Date().toISOString()}}catch(e){if(valid()){s.syncIssueCause=e instanceof RepositoryError?e.code:'unknown';s.error=e instanceof RepositoryError?e.code:'SYNC_FAILED';if(s.syncIssueCause==='authentication'){s.emit();this.auth.expire();return}s.status='offline'}}finally{if(valid())s.emit()}}
}
