import {act,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {expect,it,vi} from 'vitest';
import {App} from '../src/app/App';
import {AgendaStore} from '../src/stores/AgendaStore';
import {AuthManager} from '../src/auth/AuthManager';
import {AgendaSession} from '../src/auth/AgendaSession';
import {IndexedDBPersistence,MemoryPersistence} from '../src/offline/Persistence';
import {MemoryRepository,RepositoryError} from '../src/repositories/AgendaRepository';
import {SyncEngine} from '../src/sync/SyncEngine';
import 'fake-indexeddb/auto';
async function fixture(pending=0){const disk=new IndexedDBPersistence('m3c-ui-'+crypto.randomUUID()),auth=new AuthManager({signIn:async()=> 'A',signOut:async()=>{}});await auth.signIn();const session=new AgendaSession(auth,()=>disk),remote=new MemoryRepository();await session.attach(remote);const store=session.store!;store.repository.connectSync(null);for(let i=0;i<pending;i++)await store.create('Task',{title:'Pending '+i});store.repository.connectSync(session.sync);const logout=vi.fn(()=>session.logout());render(<App providedStore={store} onCloudLogout={logout}/>);return {disk,store,remote,logout,session}}
function settings(){fireEvent.click(screen.getByRole('button',{name:'Ajustes'}));fireEvent.click(screen.getByRole('button',{name:'Sincronización'}))}
it('M3C cloud settings and mobile status use human labels, polite announcements, no technical identity',async()=>{await fixture();settings();expect(screen.getByRole('heading',{name:'Cuenta'})).toBeInTheDocument();expect(screen.getByText('Google conectado')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Cerrar sesión'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Cerrar agenda'})).toBeNull();expect(screen.getAllByRole('status').every(el=>el.getAttribute('aria-live')==='polite')).toBe(true);expect(screen.queryByRole('alert')).toBeNull();expect(screen.getByRole('navigation',{name:'Navegación móvil'})).toBeInTheDocument();expect(document.body.textContent).not.toMatch(/UID|projectId|token|firebase:/)});
it.each(['Sincronizar','Sincronizar ahora'])('M3C %s drains pending operations safely',async button=>{const {store,remote}=await fixture(1);settings();const fetch=vi.spyOn(remote,'fetchChanges');fireEvent.click(screen.getByRole('button',{name:button}));await waitFor(()=>expect(store.outbox).toEqual([]));expect(fetch).toHaveBeenCalledOnce();expect(screen.getByText(/^Última sincronización:/)).toBeInTheDocument()});
it('M3C logout without pending changes closes without a decision',async()=>{const {logout}=await fixture();settings();fireEvent.click(screen.getByRole('button',{name:'Cerrar sesión'}));await waitFor(()=>expect(logout).toHaveBeenCalledOnce());expect(screen.queryByRole('dialog')).toBeNull()});
it('M3C logout syncs pending changes before closing',async()=>{const {store,logout,remote}=await fixture(1);settings();fireEvent.click(screen.getByRole('button',{name:'Cerrar sesión'}));await waitFor(()=>expect(logout).toHaveBeenCalledOnce());expect(store.outbox).toEqual([]);expect((await remote.fetchChanges()).entities).toHaveLength(1);expect(screen.queryByRole('dialog')).toBeNull()});
it('M3C offline logout requires decision; forced logout preserves IndexedDB scope and outbox',async()=>{const {disk,store,logout,remote}=await fixture(2);const original=store.snapshot();vi.spyOn(remote,'fetchChanges').mockRejectedValue(new RepositoryError('network'));settings();fireEvent.click(screen.getByRole('button',{name:'Cerrar sesión'}));const dialog=await screen.findByRole('dialog',{name:'Cerrar sesión con cambios pendientes'});expect(dialog).toHaveTextContent('Hay 2 cambios pendientes que todavía no han llegado a tu cuenta.');expect(logout).not.toHaveBeenCalled();expect(screen.getByRole('navigation',{name:'Navegación móvil',hidden:true})).toHaveAttribute('inert');await waitFor(()=>expect(within(dialog).getByRole('button',{name:'Esperar y reintentar'})).toHaveFocus());fireEvent.click(within(dialog).getByRole('button',{name:'Cerrar sesión igualmente'}));await waitFor(()=>expect(logout).toHaveBeenCalledOnce());expect((await disk.load()).outbox).toEqual(original.outbox);const reopened=new AgendaStore(disk);await reopened.boot();expect(reopened.entities).toEqual(original.entities);expect(reopened.outbox).toEqual(original.outbox)});
it('M3C wait and retry can sync before logout without discarding anything',async()=>{const {logout,remote}=await fixture(1);const fetch=vi.spyOn(remote,'fetchChanges').mockRejectedValueOnce(new RepositoryError('network'));settings();fireEvent.click(screen.getByRole('button',{name:'Cerrar sesión'}));await screen.findByRole('dialog');fetch.mockRestore();fireEvent.click(screen.getByRole('button',{name:'Esperar y reintentar'}));await waitFor(()=>expect(logout).toHaveBeenCalledOnce());expect((await remote.fetchChanges()).entities).toHaveLength(1)});
it('M3C cancel pending logout keeps the active account',async()=>{const {logout,remote,session}=await fixture(1);vi.spyOn(remote,'fetchChanges').mockRejectedValue(new RepositoryError('network'));settings();fireEvent.click(screen.getByRole('button',{name:'Cerrar sesión'}));await screen.findByRole('dialog');fireEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(screen.queryByRole('dialog')).toBeNull();expect(logout).not.toHaveBeenCalled();expect(session.auth.state).toBe('signedIn')});
it('M3C permanent failure diagnosis offers retry and opening the affected item; never discards',async()=>{const {store,remote}=await fixture(1);vi.spyOn(remote,'save').mockRejectedValueOnce(new RepositoryError('permission'));await act(()=>new SyncEngine(store,remote,newAuth()).sync());settings();expect(screen.getByRole('alert')).toHaveTextContent('Necesita atención');expect(screen.getByText(/1 cambios con error permanente/)).toHaveTextContent('Los cambios posteriores');expect(screen.queryByRole('button',{name:/vaciar|descartar/i})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Abrir elemento'}));expect(screen.getByRole('dialog')).toHaveTextContent('Editar tarea');fireEvent.click(screen.getByRole('button',{name:'Cerrar'}));fireEvent.click(screen.getByRole('button',{name:'Reintentar'}));await waitFor(()=>expect(store.outbox).toEqual([]));expect((await remote.fetchChanges()).entities).toHaveLength(1)});
function newAuth(){const auth=new AuthManager({signIn:async()=> 'A',signOut:async()=>{}});auth.identity='A';auth.state='signedIn';return auth}
it('M3C local UI retains refresh and hides remote lastSync, pending and attention',async()=>{const store=new AgendaStore(new MemoryPersistence(),undefined,'local-only');await store.boot();store.status='offline';store.lastSync='2026-10-07T10:00:00Z';store.syncIssueCause='permission';render(<App providedStore={store}/>);settings();expect(screen.getByRole('button',{name:'Refrescar agenda local'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Cerrar agenda'})).toBeInTheDocument();expect(screen.queryByText(/^Última sincronización:/)).toBeNull();expect(document.body.textContent).not.toMatch(/cambios pendientes|Necesita atención|Sin conexión/);fireEvent.click(screen.getByRole('button',{name:'Datos y recuperación'}));fireEvent.click(screen.getByRole('button',{name:'Comprobar integridad'}));expect(screen.getByRole('alert')).not.toHaveTextContent('pendientes')});
