import {it,expect} from 'vitest';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence} from '../src/offline/Persistence';
import type {Snapshot} from '../src/offline/Persistence';
import {createEntity,updateEntity,merge,clone} from '../src/models/entities';
import {serialize,deserialize,migrate} from '../src/models/serialization';
import {CloudKitRepository,MockCloudGateway,encode} from '../src/cloud/CloudGateway';
import {SyncEngine} from '../src/sync/SyncEngine';
import {localAuth} from '../src/auth/AuthManager';
import {exportBackup,previewImport} from '../src/backup/backup';
import {generateWorker} from '../scripts/service-worker';
async function store(p=new MemoryPersistence()){const s=new AgendaStore(p);await s.boot();return s}
it('serializes V1 and rejects unsupported migrations',()=>{const e=createEntity('Task');expect(deserialize(serialize(e))).toEqual(e);expect(()=>migrate({...e,schemaVersion:2})).toThrow()});
it('normalizes titles and duplicate labels on create',async()=>{const s=await store(),label=await s.create('Label');const e=await s.create('Task',{title:'  Synthetic  ',labelIDs:[label.id,label.id]});expect(e.fields.title).toBe('Synthetic');expect(e.fields.labelIDs).toEqual([label.id])});
it('equal field clock collision is commutative',()=>{const a=createEntity('Task'),b=clone(a);b.fields.title='Conflicting source';expect(merge(a,b)).toEqual(merge(b,a))});
it('bulk today tomorrow priority labels and reorder preserve clocks',async()=>{const s=await store(),a=await s.create('Task'),b=await s.create('Task'),l=await s.create('Label');await s.service.schedule([a.id,b.id],1,'Europe/Madrid','2026-03-28T08:00:00.000Z');await s.service.priority([a.id,b.id],3);await s.service.labels([a.id,b.id],[l.id]);await s.service.reorder([b.id,a.id]);expect(s.entities.find(e=>e.id===a.id)?.fields).toMatchObject({due:'2026-03-29T07:00:00.000Z',priority:3,labelIDs:[l.id],sortOrder:1})});
it('delete completed is a reversible tombstone batch',async()=>{const s=await store(),a=await s.create('Task'),b=await s.create('Task');await s.complete(a.id,true);await s.service.deleteCompleted();expect(s.entities.find(e=>e.id===a.id)?.lifecycle).toBe('deleted');expect(s.entities.find(e=>e.id===b.id)?.lifecycle).toBe('active');await s.undo();expect(s.entities.every(e=>e.lifecycle==='active')).toBe(true)});
it('undo and redo preserve remote changes to other fields',async()=>{const s=await store(),a=await s.create('Task',{title:'Original'});await s.patch(a.id,{title:'Local'});await s.remote([updateEntity(s.entities[0],{priority:3},'remote')]);await s.undo();expect(s.entities[0].fields).toMatchObject({title:'Original',priority:3});await s.redo();expect(s.entities[0].fields).toMatchObject({title:'Local',priority:3});await s.undo();expect(s.entities[0].fields).toMatchObject({title:'Original',priority:3})});
it('undo cannot overwrite a newer remote change on the same field',async()=>{const s=await store(),a=await s.create('Task');await s.patch(a.id,{title:'Local'});await s.remote([updateEntity(s.entities[0],{title:'Remote'},'remote')]);await s.undo();expect(s.entities[0].fields.title).toBe('Remote')});
it('clears selection filters history cursor and diagnostics on detach',async()=>{const s=await store(),a=await s.create('Task');s.setSelection([a.id]);s.setFilters({query:'Synthetic'});s.cursor='cursor';s.error='error';s.detach();expect(s.selection).toEqual([]);expect(s.filters).toEqual({});expect(s.cursor).toBeUndefined();expect(s.errors).toEqual([]);await s.undo();expect(s.entities).toEqual([])});
it('purge requires confirmation and acknowledgement and stays separate from deletion',async()=>{const s=await store(),a=await s.create('Task');await s.service.delete(a.id);await expect(s.purge([a.id],'')).rejects.toThrow('CONFIRMATION_REQUIRED');await expect(s.purge([a.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');for(const op of [...s.outbox])await s.remote([],undefined,op.operationID);await expect(s.purge([a.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');expect(s.entities[0].lifecycle).toBe('deleted');expect((await s.persistence.load()).entities).toHaveLength(1)});
it('purge cannot orphan a referenced task',async()=>{const s=await store(),a=await s.create('Task');await s.create('Subtask',{parentTaskId:a.id});await s.service.delete(a.id);for(const op of [...s.outbox])await s.remote([],undefined,op.operationID);await expect(s.purge([a.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED')});
it('recovered duplicate outbox operation is sent only once',async()=>{const s=await store();await s.create('Task');const snapshot=s.snapshot();snapshot.outbox.push(clone(snapshot.outbox[0]));await s.persistence.save(snapshot);await s.boot();expect(s.outbox).toHaveLength(1)});
it('offline create survives a failed send and reconnects',async()=>{const s=await store(),auth=localAuth(),gateway=new MockCloudGateway();await auth.signIn();await s.create('Task');const sync=new SyncEngine(s,new CloudKitRepository(gateway),auth);gateway.save=async()=>{throw Error('offline')};await sync.sync();expect(s.outbox[0].status).toBe('retry');gateway.save=MockCloudGateway.prototype.save.bind(gateway);await s.markOperation(s.outbox[0].operationID,{nextAttemptAt:0});await sync.sync();expect(s.outbox).toEqual([]);expect(gateway.records.size).toBe(1);expect(s.lastSync).not.toBeNull()});
it('two browsers converge after independent edits and deletion',async()=>{const a=await store(),b=await store(),auth=localAuth(),g=new MockCloudGateway();await auth.signIn();const sa=new SyncEngine(a,new CloudKitRepository(g),auth),sb=new SyncEngine(b,new CloudKitRepository(g),auth);const task=await a.create('Task');await sa.sync();await sb.sync();await a.patch(task.id,{title:'A'});await b.patch(task.id,{priority:3});await sa.sync();await sb.sync();await sa.sync();expect(a.entities).toEqual(b.entities);await a.service.delete(task.id);await b.patch(task.id,{notes:'Offline edit'});await sa.sync();await sb.sync();await sa.sync();expect(a.entities).toEqual(b.entities);expect(a.entities[0].lifecycle).toBe('deleted');await b.service.restore(task.id);await sb.sync();await sa.sync();expect(a.entities[0].lifecycle).toBe('active')});
it('CAS stale persistence merges both local tabs without dropping outbox',async()=>{class StaleOnce extends MemoryPersistence {other:Snapshot|null=null;override async save(s:Snapshot){if(this.other){const other=this.other;this.other=null;await super.save(other);throw Error('STORAGE_WRITE_ABORTED_OR_ANOTHER_TAB')}return super.save(s)}}const p=new StaleOnce(),a=await store(p);const first=await a.create('Task');const remote=clone(a.snapshot());remote.entities[0]=updateEntity(remote.entities[0],{title:'Other tab'},'other');const b=await store();const extra=await b.create('Task');remote.entities.push(extra);remote.outbox.push(...b.outbox);p.other=remote;await a.patch(first.id,{priority:3});expect(a.entities).toHaveLength(2);expect(a.entities.find(e=>e.id===first.id)?.fields).toMatchObject({title:'Other tab',priority:3});expect(a.outbox).toHaveLength(3)});
it('CloudKit common and indexed fields are encoded',()=>{const e=createEntity('Task',{due:'2026-10-01T07:00:00.000Z'}),r=encode(e);expect(r.fields.lifecycle.value).toBe('active');expect(r.fields.dueAt.value).toBe(e.fields.due);expect(JSON.parse(r.fields.fieldClocksJSON.value as string)).toEqual(e.fieldClocks);expect(r.fields.parentTaskId).toBeUndefined()});
it('import preview reports creates updates and tombstones',async()=>{const a=createEntity('Task'),b=createEntity('Task'),c=createEntity('Task'),backup=await exportBackup([a,c]);expect(previewImport([a,b],backup,'replace')).toEqual({create:1,update:1,delete:1})});
it('SW updates wait for existing clients and never force reload during a critical operation',()=>{const worker=generateWorker(['./'],'next');expect(worker).not.toMatch(/skipWaiting|clients\.claim|\.reload/);expect(worker).toContain("addEventListener('install'")});

it('a field edit does not advance clocks of unchanged fields',()=>{const a=createEntity('Task',{title:'Synthetic'}),b=updateEntity(a,{...a.fields,priority:2},'writer');expect(b.fieldClocks.title).toEqual(a.fieldClocks.title);expect(b.fieldClocks.priority).not.toEqual(a.fieldClocks.priority)});

it('editor patches contain only fields changed in the draft',async()=>{const {diffFields}=await import('../src/models/serialization');const entity=createEntity('Task');expect(diffFields(entity.fields,{...entity.fields,title:'Edited'})).toEqual({title:'Edited'})});
it('timed event covers both civil days and excludes an exclusive midnight end',async()=>{const {occurrences,coversDate}=await import('../src/utils/calendar');const e=createEntity('Event',{start:'2026-09-25T21:00:00.000Z',end:'2026-09-26T01:00:00.000Z',timezone:'Europe/Madrid'});const o=occurrences(e,'2026-09-25','2026-09-27')[0];expect(coversDate(o,'2026-09-25')).toBe(true);expect(coversDate(o,'2026-09-26')).toBe(true);o.end='2026-09-25T22:00:00.000Z';expect(coversDate(o,'2026-09-26')).toBe(false)});
it('session logout stops sync and detaches its private store',async()=>{const {AgendaSession}=await import('../src/auth/AgendaSession');const {MemoryRepository}=await import('../src/repositories/AgendaRepository');const auth=localAuth();await auth.signIn();const session=new AgendaSession(auth,()=>new MemoryPersistence());await session.attach(new MemoryRepository());const s=session.store!;s.setFilters({query:'Synthetic'});await session.logout();expect(session.store).toBeNull();expect(session.sync).toBeNull();expect(s.status).toBe('signedOut');expect(s.filters).toEqual({});expect(s.outbox).toEqual([])});
it('mock auth checks existing sessions without signing in',async()=>{const {AuthManager,MockAuthProvider}=await import('../src/auth/AuthManager');const auth=new AuthManager(new MockAuthProvider());await auth.check();expect(auth.state).toBe('signedOut');await auth.signIn();await auth.check();expect(auth.state).toBe('signedIn')});
it('calendar uses the display timezone without shifting all-day civil dates',async()=>{const {occurrences,coversDate}=await import('../src/utils/calendar');const e=createEntity('Event',{start:'2026-09-26T00:00:00.000Z',end:'2026-09-26T01:00:00.000Z',timezone:'Europe/Madrid'});const o=occurrences(e,'2026-09-25','2026-09-27')[0];expect(coversDate(o,'2026-09-25','America/Los_Angeles')).toBe(true);expect(coversDate(o,'2026-09-26','America/Los_Angeles')).toBe(false);const allDay=createEntity('Event',{allDay:true,startDate:'2026-09-26',endDate:'2026-09-27'});expect(coversDate(occurrences(allDay,'2026-09-25','2026-09-27')[0],'2026-09-26','America/Los_Angeles')).toBe(true)});
