import 'fake-indexeddb/auto';
import {it,expect} from 'vitest';
import {IndexedDBPersistence} from '../src/offline/Persistence';
import {AgendaStore} from '../src/stores/AgendaStore';
import {createEntity} from '../src/models/entities';
import type {Entity} from '../src/models/entities';
async function scoped(identity=crypto.randomUUID()){const s=new AgendaStore(new IndexedDBPersistence(identity));await s.boot();return s}
it('IndexedDB atomically preserves entities and outbox across offline reopen',async()=>{const id=crypto.randomUUID(),a=await scoped(id);await a.create('Task',{title:'Synthetic'});const b=await scoped(id);expect(b.entities).toEqual(a.entities);expect(b.outbox).toEqual(a.outbox)});
it('IndexedDB isolates entities outbox cursor preferences and quarantine by user',async()=>{const a=await scoped(),b=await scoped();await a.create('Task');await a.create('Preferences',{theme:'dark'});await a.remote([],'opaque',undefined,[{invalid:true}]);await b.refresh();expect(b.entities).toEqual([]);expect(b.outbox).toEqual([]);expect(b.cursor).toBeUndefined();expect(b.quarantine).toEqual([])});
it('concurrent IndexedDB tabs merge field edits and all pending operations',async()=>{const id=crypto.randomUUID(),a=await scoped(id),b=await scoped(id);const task=await a.create('Task');await b.refresh();await Promise.all([a.patch(task.id,{title:'A'}),b.patch(task.id,{priority:3})]);await a.refresh();await b.refresh();expect(a.entities).toEqual(b.entities);expect(a.entities[0].fields).toMatchObject({title:'A',priority:3});expect(a.outbox).toHaveLength(3)});
it('concurrent IndexedDB creates do not drop another tab records',async()=>{const id=crypto.randomUUID(),a=await scoped(id),b=await scoped(id);await Promise.all([a.create('Task'),b.create('QuickNote')]);await a.refresh();await b.refresh();expect(a.entities).toEqual(b.entities);expect(a.entities).toHaveLength(2);expect(a.outbox).toHaveLength(2)});
it('quarantine is stored separately and survives reopening',async()=>{const id=crypto.randomUUID(),p=new IndexedDBPersistence(id);await p.load();await p.save({entities:[createEntity('Task'),{} as Entity],outbox:[],quarantine:[]});const s=new AgendaStore(p);await s.boot();expect(s.quarantine).toHaveLength(1);await s.create('Task');const next=await scoped(id);expect(next.quarantine).toHaveLength(1);expect(next.entities).toHaveLength(2)});
it('an acknowledged operation is not resurrected by a stale tab',async()=>{const id=crypto.randomUUID(),a=await scoped(id),b=await scoped(id);const t=await a.create('Task');await b.refresh();await a.remote([],undefined,a.outbox[0].operationID);await b.patch(t.id,{priority:1});expect(b.outbox).toHaveLength(1);expect(b.outbox[0].payload.fields.priority).toBe(1)});
it('a scope clear leaves other users intact',async()=>{const a=await scoped(),b=await scoped();await a.create('Task');await b.create('QuickNote');await a.persistence.clear();await a.refresh();await b.refresh();expect(a.entities).toHaveLength(0);expect(b.entities).toHaveLength(1)});
