import 'fake-indexeddb/auto';
import {describe,it,expect,vi} from 'vitest';
import {createEntity,updateEntity,clone} from '../src/models/entities';
import {integrity} from '../src/recovery/integrity';
import {purgeDependencies,resolveDeletedLabel} from '../src/recovery/purgeDependencies';
import {exportBackup,parseBackup,importBackup,backupEntities} from '../src/backup/backup';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence,IndexedDBPersistence} from '../src/offline/Persistence';
const deleted=(e:ReturnType<typeof createEntity>)=>updateEntity(e,{},'test','deleted');
async function store(){const s=new AgendaStore(new MemoryPersistence(),'test','local-only');await s.boot();return s}
const codes=(entities:Parameters<typeof integrity>[0])=>integrity(entities).issues.map(i=>i.code);
describe('M3B integrity and recovery',()=>{
 it('deleted label warns; restore clears it without mutating records',()=>{const l=createEntity('Label'),t=createEntity('Task',{labelIDs:[l.id]}),before=clone(t);expect(codes([deleted(l),t])).toContain('DELETED_LABEL_REFERENCE');expect(codes([l,t])).toEqual([]);expect(t).toEqual(before)});
 it('explicit resolution preserves other labels and allows purge',async()=>{const s=await store(),l=createEntity('Label'),other=createEntity('Label'),t=createEntity('Task',{labelIDs:[l.id,other.id]});await s.commit([deleted(l),other,t]);await s.resolveLabelReferences(l.id);expect(s.entities.find(e=>e.id===t.id)?.fields.labelIDs).toEqual([other.id]);await s.purge([l.id],'PURGAR');expect(codes(s.entities)).toEqual([])});
 it('template labels warn and resolve preserving unrelated values',()=>{const l=createEntity('Label'),other=createEntity('Label'),t=createEntity('Template',{name:'sample',definition:{targetKind:'Task',values:{title:'keep',labelIDs:[l.id,other.id]}}});expect(codes([deleted(l),other,t])).toContain('DELETED_LABEL_REFERENCE');const [resolved]=resolveDeletedLabel([deleted(l),other,t],l.id,'test');expect(resolved.kind==='Template'&&resolved.fields.definition.values).toEqual({title:'keep',labelIDs:[other.id]})});
 it('active child label warns and explicit recovery unlinks parent',()=>{const l=createEntity('Label'),child=createEntity('Label',{parentLabelId:l.id});expect(codes([deleted(l),child])).toContain('DELETED_PARENT_REFERENCE');expect(resolveDeletedLabel([deleted(l),child],l.id,'test')[0].fields.parentLabelId).toBeNull()});
 it('active subtask warns and blocks deleted task purge',async()=>{const s=await store(),t=createEntity('Task'),sub=createEntity('Subtask',{parentTaskId:t.id});await s.commit([deleted(t),sub]);expect(codes(s.entities)).toContain('DELETED_PARENT_REFERENCE');expect(purgeDependencies(s.entities,[t.id]).activeBlockers).toEqual([sub]);await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_REFERENCED')});
 it('deleted task and subtask require explicit joint purge and clear history',async()=>{const s=await store(),t=createEntity('Task'),sub=createEntity('Subtask',{parentTaskId:t.id});await s.commit([deleted(t),deleted(sub)]);await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_REFERENCED');await s.purge(purgeDependencies(s.entities,[t.id]).expandedPurgeSet,'PURGAR');await s.undo();await s.redo();expect(s.entities).toEqual([])});
 it('transitive closure terminates even for label cycles and finds active blockers',()=>{const a=createEntity('Label'),b=createEntity('Label',{parentLabelId:a.id}),c=createEntity('Label',{parentLabelId:b.id}),t=createEntity('Task',{labelIDs:[c.id]});const cyclic=updateEntity(a,{parentLabelId:c.id},'test');const report=purgeDependencies([deleted(cyclic),deleted(b),deleted(c),t],[a.id]);expect(report.expandedPurgeSet).toEqual([a.id,b.id,c.id]);expect(report.deletedDependencies).toHaveLength(2);expect(report.activeBlockers).toEqual([t]);expect(codes([cyclic,b,c])).toContain('LABEL_CYCLE')});
 it('joint indexeddb purge rolls back disk, memory and history atomically',async()=>{const s=new AgendaStore(new IndexedDBPersistence(crypto.randomUUID()),'test','local-only');await s.boot();const t=createEntity('Task'),sub=createEntity('Subtask',{parentTaskId:t.id});await s.commit([deleted(t),deleted(sub)]);const before=s.snapshot(),put=IDBObjectStore.prototype.put;const spy=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args:Parameters<IDBObjectStore['put']>){const result=put.apply(this,args);if(this.name==='outbox')this.transaction.abort();return result});try{await expect(s.purge([t.id,sub.id],'PURGAR')).rejects.toThrow()}finally{spy.mockRestore()}expect(s.snapshot()).toEqual(before);expect(await s.persistence.load()).toEqual(before);await s.undo();expect(s.entities).toHaveLength(2)});
 it('recoverable warnings survive backup parse and restore',async()=>{const l=createEntity('Label'),t=createEntity('Task',{labelIDs:[l.id]}),s=await store();const b=await exportBackup([deleted(l),t]);const parsed=await parseBackup(JSON.stringify(b));expect(codes(backupEntities(parsed))).toContain('DELETED_LABEL_REFERENCE');await importBackup(s,parsed,'merge');expect(codes(s.entities)).toContain('DELETED_LABEL_REFERENCE')});
 it('duplicate valid preferences warn and permit backup without consolidation',async()=>{const entities=[createEntity('Preferences'),createEntity('Preferences')];expect(codes(entities)).toContain('DUPLICATE_PREFERENCES');expect((await parseBackup(JSON.stringify(await exportBackup(entities)))).preferences).toHaveLength(2)});
 it('invalid records and duplicate identity still block export and parse',async()=>{const t=createEntity('Task');await expect(exportBackup([t,clone(t)])).rejects.toThrow('INTEGRITY_FAILED');await expect(exportBackup([{...t,id:'bad'}])).rejects.toThrow('INTEGRITY_FAILED');const b=await exportBackup([t]);b.tasks[0].id='bad';const bytes=new TextEncoder().encode(JSON.stringify(backupEntities(b)));b.checksum=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');await expect(parseBackup(JSON.stringify(b))).rejects.toThrow('INTEGRITY_FAILED')});
 it('checksum corruption remains blocked',async()=>{const b=await exportBackup([createEntity('Task')]);b.checksum='bad';await expect(parseBackup(JSON.stringify(b))).rejects.toThrow('CHECKSUM_FAILED')});
 it('replace can produce previous backup with local recoverable warnings',async()=>{const s=await store(),l=createEntity('Label'),t=createEntity('Task',{labelIDs:[l.id]});await s.commit([deleted(l),t]);const previous=await importBackup(s,await exportBackup([]),'replace','REEMPLAZAR');expect(codes(backupEntities(previous))).toContain('DELETED_LABEL_REFERENCE')});
 it('quarantine blocks export workflow and never enters backup V2',async()=>{const s=await store();s.quarantine=[{code:'INVALID_RECORD',entity:{id:'bad'}}];await expect(importBackup(s,await exportBackup([]),'replace','REEMPLAZAR')).rejects.toThrow('INTEGRITY_FAILED');expect(await exportBackup([])).not.toHaveProperty('quarantine')});
 it('sync-enabled preserves tombstones even after acknowledgement',async()=>{const s=new AgendaStore(new MemoryPersistence());await s.boot();const t=await s.create('Task');await s.service.delete(t.id);for(const op of [...s.outbox])await s.remote([],undefined,op.operationID);await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');expect(s.entities[0].lifecycle).toBe('deleted')});
});
