import 'fake-indexeddb/auto';
import {expect,it,vi} from 'vitest';
import {AgendaStore} from '../src/stores/AgendaStore';
import {IndexedDBPersistence,MemoryPersistence} from '../src/offline/Persistence';
import type {Persistence} from '../src/offline/Persistence';
import {exportBackup,backupEntities} from '../src/backup/backup';
async function local(p:Persistence=new IndexedDBPersistence(crypto.randomUUID())){const s=new AgendaStore(p,crypto.randomUUID(),'local-only');await s.boot();expect(s.status).toBe('ready');return s}
async function clean(s:AgendaStore){expect(s.outbox).toEqual([]);expect(s.cursor).toBeUndefined();const disk=await s.persistence.load();expect(disk.outbox).toEqual([]);expect(disk.cursor).toBeUndefined()}
it('create, edit, 100 concurrent edits and QuickNote autosaves never queue remote operations',async()=>{const s=await local(),t=await s.create('Task',{title:'initial'}),n=await s.create('QuickNote');await s.patch(t.id,{title:'edited'});await Promise.all(Array.from({length:100},(_,i)=>s.patch(n.id,{text:`autosave ${i}`} )));expect(s.entities.find(e=>e.id===n.id)?.fields.text).toBe('autosave 99');await clean(s);const reopened=await local(s.persistence);expect(reopened.entities).toEqual(s.entities);await clean(reopened)});
it('deleteCompleted moves completed tasks to trash without a dead queue',async()=>{const s=await local(),t=await s.create('Task');await s.complete(t.id,true);await s.service.deleteCompleted();expect(s.entities[0].lifecycle).toBe('deleted');await clean(s);await s.purge([t.id],'PURGAR');expect(s.entities).toEqual([]);await clean(s)});
it('purge requires confirmation and deleted lifecycle and clears undo/redo',async()=>{const s=await local(),t=await s.create('Task');await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');await s.service.delete(t.id);await expect(s.purge([t.id],'yes')).rejects.toThrow('CONFIRMATION_REQUIRED');await s.undo();await s.redo();await s.purge([t.id],'PURGAR');await s.undo();await s.redo();expect(s.entities).toEqual([]);await clean(s)});
it('undo/redo preserves edits and lifecycle without outbox',async()=>{const s=await local(),t=await s.create('Task',{title:'before'});await s.patch(t.id,{title:'after'});await s.undo();expect(s.entities[0].fields.title).toBe('before');await s.redo();expect(s.entities[0].fields.title).toBe('after');await s.service.delete(t.id);await s.undo();expect(s.entities[0].lifecycle).toBe('active');await s.redo();expect(s.entities[0].lifecycle).toBe('deleted');await clean(s)});
it('purge protects references including references written by a stale tab',async()=>{const scope=crypto.randomUUID(),a=await local(new IndexedDBPersistence(scope)),b=await local(new IndexedDBPersistence(scope)),t=await a.create('Task');await a.service.delete(t.id);await b.refresh();await b.create('Subtask',{parentTaskId:t.id});await expect(a.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_REFERENCED');expect((await a.persistence.load()).entities).toHaveLength(2)});
it('purge sees a concurrent restore instead of removing it',async()=>{const scope=crypto.randomUUID(),a=await local(new IndexedDBPersistence(scope)),t=await a.create('Task');await a.service.delete(t.id);const b=await local(new IndexedDBPersistence(scope));await b.service.restore(t.id);await expect(a.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED')});
it('atomic purge rollback retains disk, memory and history',async()=>{const s=await local(),t=await s.create('Task');await s.service.delete(t.id);const before=s.snapshot(),put=IDBObjectStore.prototype.put;const spy=vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args:Parameters<IDBObjectStore['put']>){const result=put.apply(this,args);if(this.name==='outbox')this.transaction.abort();return result});try{await expect(s.purge([t.id],'PURGAR')).rejects.toThrow()}finally{spy.mockRestore()}expect(s.snapshot()).toEqual(before);expect(await s.persistence.load()).toEqual(before);await s.undo();expect(s.entities[0].lifecycle).toBe('active')});
it('two local tabs merge concurrent fields and concurrent creates',async()=>{const scope=crypto.randomUUID(),a=await local(new IndexedDBPersistence(scope)),b=await local(new IndexedDBPersistence(scope)),t=await a.create('Task');await b.refresh();await Promise.all([a.patch(t.id,{title:'A'}),b.patch(t.id,{priority:3})]);await Promise.all([a.create('QuickNote'),b.create('Task')]);await a.refresh();await b.refresh();expect(a.entities).toEqual(b.entities);expect(a.entities.find(e=>e.id===t.id)?.fields).toMatchObject({title:'A',priority:3});expect(a.entities).toHaveLength(3);await clean(a);await clean(b)});
for(const phase of ['boot','refresh','commit','remote','markOperation'] as const)it(`discards 1.0 legacy transport on ${phase} without losing entities or quarantine`,async()=>{const scope=crypto.randomUUID(),p=new IndexedDBPersistence(scope),old=new AgendaStore(p);await old.boot();const t=await old.create('Task',{title:'legacy'});await old.remote([],'legacy-cursor',undefined,[{invalid:true}]);const before=old.snapshot();const s=new AgendaStore(new IndexedDBPersistence(scope),undefined,'local-only');if(phase==='boot')await s.boot();else{await s.boot();await old.refresh();await old.patch(t.id,{priority:2});await old.remote([],'rewritten');if(phase==='refresh')await s.refresh();if(phase==='commit')await s.patch(t.id,{title:'new'});if(phase==='remote')await s.remote([],'ignored');if(phase==='markOperation')await s.markOperation('missing',{status:'retry'});expect(s.entities[0].fields.priority).toBe(2)}expect(s.quarantine).toEqual(before.quarantine);expect(s.entities[0].id).toBe(t.id);await clean(s)});
it('mixed 1.0/1.1 conflict recovery preserves fields while removing rewritten outbox/cursor',async()=>{const scope=crypto.randomUUID(),s=await local(new IndexedDBPersistence(scope)),t=await s.create('Task'),old=new AgendaStore(new IndexedDBPersistence(scope));await old.boot();await old.patch(t.id,{priority:3});await old.remote([],'old-cursor');const save=vi.spyOn(s.persistence,'save');await s.patch(t.id,{title:'new'});expect(save.mock.calls.length).toBeGreaterThan(1);expect(s.entities[0].fields).toMatchObject({priority:3,title:'new'});await clean(s);await old.refresh();await old.patch(t.id,{notes:'1.0 still writes'});expect((await old.persistence.load()).outbox).toHaveLength(1);await s.refresh();expect(s.entities[0].fields.notes).toBe('1.0 still writes');await clean(s)});
it('sync-enabled still queues saves and blocks purge until every operation is acknowledged',async()=>{const s=new AgendaStore(new MemoryPersistence(),undefined,'sync-enabled');await s.boot();const t=await s.create('Task');await s.service.delete(t.id);expect(s.outbox).toHaveLength(2);await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');for(const op of [...s.outbox])await s.remote([],'cloud-cursor',op.operationID);await expect(s.purge([t.id],'PURGAR')).rejects.toThrow('PURGE_NOT_ACKNOWLEDGED');expect(s.entities[0].lifecycle).toBe('deleted');expect(s.cursor).toBe('cloud-cursor')});
it('local cleanup leaves Firebase scope entities, queue, cursor and quarantine intact',async()=>{const scope=crypto.randomUUID(),cloud=new AgendaStore(new IndexedDBPersistence('firebase:'+scope),undefined,'sync-enabled');await cloud.boot();await cloud.create('Task');await cloud.remote([],'firebase',undefined,[{invalid:true}]);const before=cloud.snapshot();const s=await local(new IndexedDBPersistence('local:'+scope));await s.create('Task');await s.refresh();expect(await cloud.persistence.load()).toEqual(before)});
it('cleanup keeps backup entities, clocks, lifecycle, references, templates, scheduling and quarantine identical',async()=>{const p=new IndexedDBPersistence(crypto.randomUUID()),old=new AgendaStore(p);await old.boot();const label=await old.create('Label',{title:'label'}),t=await old.create('Task',{labelIDs:[label.id]});await old.service.scheduleTask(t.id,'2026-10-05T08:00:00.000Z',60,'Europe/Madrid');await old.complete(t.id,true);await old.create('Subtask',{parentTaskId:t.id});await old.create('Template',{name:'template',definition:{targetKind:'Task',values:{title:'default'}}});await old.create('Preferences',{theme:'dark'});const n=await old.create('QuickNote');await old.service.delete(n.id);await old.remote([],'legacy',undefined,[{invalid:true}]);const before=old.snapshot(),backup=await exportBackup(old.entities);const s=await local(p);expect(s.entities).toEqual(before.entities);expect(s.quarantine).toEqual(before.quarantine);expect(backupEntities(await exportBackup(s.entities))).toEqual(backupEntities(backup));await clean(s)});
it('local commit failure rolls back without operations and cleanup failure enters safe mode',async()=>{const p=new MemoryPersistence(),s=await local(p),t=await s.create('Task');const before=s.snapshot(),spy=vi.spyOn(p,'save').mockRejectedValueOnce(Error('STORAGE_WRITE_FAILED'));await expect(s.patch(t.id,{title:'failed'})).rejects.toThrow();expect(s.snapshot()).toEqual(before);spy.mockRestore();const old=new AgendaStore(p);await old.boot();await old.patch(t.id,{title:'legacy'});vi.spyOn(p,'save').mockRejectedValueOnce(Error('failure'));const next=new AgendaStore(p,undefined,'local-only');await next.boot();expect(next.status).toBe('safe');expect(next.outbox).toEqual([]);expect((await p.load()).entities[0].fields.title).toBe('legacy')});
it('purge aborts atomically when another tab adds a reference between read and save',async()=>{const scope=crypto.randomUUID(),a=await local(new IndexedDBPersistence(scope)),t=await a.create('Task');await a.service.delete(t.id);const b=await local(new IndexedDBPersistence(scope)),save=a.persistence.save.bind(a.persistence);const spy=vi.spyOn(a.persistence,'save').mockImplementationOnce(async(...args)=>{await b.create('Subtask',{parentTaskId:t.id});return save(...args)});try{await expect(a.purge([t.id],'PURGAR')).rejects.toThrow('STORAGE_WRITE_ABORTED_OR_ANOTHER_TAB')}finally{spy.mockRestore()}expect((await a.persistence.load()).entities).toHaveLength(2);await a.undo();expect(a.entities.find(e=>e.id===t.id)?.lifecycle).toBe('active');await clean(a)});
it('cleanup retries after a mixed-tab write during boot without losing new entities',async()=>{const scope=crypto.randomUUID(),old=new AgendaStore(new IndexedDBPersistence(scope));await old.boot();await old.create('Task');await old.remote([],'old');const p=new IndexedDBPersistence(scope),save=p.save.bind(p);vi.spyOn(p,'save').mockImplementationOnce(async(...args)=>{await old.create('QuickNote',{text:'concurrent'});return save(...args)});const s=await local(p);expect(s.entities).toHaveLength(2);expect(s.entities.find(e=>e.kind==='QuickNote')?.fields.text).toBe('concurrent');await clean(s)});
it('cleanup invalidation during revision recovery cannot write to a detached session',async()=>{const scope=crypto.randomUUID(),p=new IndexedDBPersistence(scope),old=new AgendaStore(p);await old.boot();await old.create('Task');const before=old.snapshot(),s=new AgendaStore(p,undefined,'local-only'),load=p.load.bind(p);const save=vi.spyOn(p,'save').mockRejectedValueOnce(Error('STORAGE_WRITE_ABORTED_OR_ANOTHER_TAB'));vi.spyOn(p,'load').mockImplementationOnce(load).mockImplementationOnce(async()=>{const disk=await load();s.detach();return disk});await s.boot();expect(save).toHaveBeenCalledTimes(1);expect(s.status).toBe('signedOut');expect(await new IndexedDBPersistence(scope).load()).toEqual(before)});
