import {fireEvent,render,screen,waitFor,cleanup} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {App} from '../src/app/App';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence} from '../src/offline/Persistence';
afterEach(cleanup);
it('local QuickNote UI autosaves with zero outbox and shows browser storage status',async()=>{const p=new MemoryPersistence(),s=new AgendaStore(p,undefined,'local-only');await s.boot();render(<App providedStore={s}/>);expect(screen.getByText('Guardada en este navegador')).toBeInTheDocument();expect(screen.queryByText(/cambios guardados para sincronizar/)).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Notas'}));fireEvent.click(screen.getByRole('button',{name:'＋ Nuevo'}));await screen.findByLabelText('Nota');fireEvent.change(screen.getByLabelText('Nota'),{target:{value:'autosaved local text'}});await waitFor(()=>expect(s.entities[0].fields.text).toBe('autosaved local text'));fireEvent.click(screen.getByRole('button',{name:'Cerrar'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());await s.flush();expect(s.outbox).toEqual([]);const reopened=new AgendaStore(p,undefined,'local-only');await reopened.boot();expect(reopened.entities).toEqual(s.entities);expect(reopened.outbox).toEqual([]);expect(reopened.cursor).toBeUndefined();fireEvent.click(screen.getByRole('button',{name:'Ajustes'}));fireEvent.click(screen.getByRole('button',{name:'Sincronización'}));expect(screen.getByText('Agenda local · Guardada en este navegador')).toBeInTheDocument();expect(screen.queryByText(/cambios pendientes/)).toBeNull()});
it('local trash UI permits confirmed purge without remote ACK',async()=>{const s=new AgendaStore(new MemoryPersistence(),undefined,'local-only');await s.boot();const t=await s.create('Task',{title:'trash fixture'});await s.service.delete(t.id);render(<App providedStore={s}/>);fireEvent.click(screen.getByRole('button',{name:'Ajustes'}));fireEvent.click(screen.getByRole('button',{name:'Datos y recuperación'}));const purge=screen.getByRole('button',{name:'Purgar'});expect(purge).toBeEnabled();const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);try{fireEvent.click(purge);await waitFor(()=>expect(s.entities).toEqual([]));expect(confirm).toHaveBeenCalledOnce()}finally{confirm.mockRestore()}});
it('App constructs its own local-only store',async()=>{render(<App/>);fireEvent.click(screen.getByRole('button',{name:'Abrir agenda local'}));await screen.findByText('Guardada en este navegador');fireEvent.click(screen.getByRole('button',{name:'＋ Nuevo'}));fireEvent.change(screen.getByLabelText('Título'),{target:{value:'default local store'}});fireEvent.click(screen.getByRole('button',{name:'Guardar'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(screen.queryByText(/cambios guardados para sincronizar/)).toBeNull()});
