import {afterEach,describe,expect,it,vi} from 'vitest';
import {AuthManager} from '../src/auth/AuthManager';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence} from '../src/offline/Persistence';
import {MemoryRepository,RepositoryError} from '../src/repositories/AgendaRepository';
import type {AgendaRepository,ChangePage} from '../src/repositories/AgendaRepository';
import {SyncEngine} from '../src/sync/SyncEngine';
import {clone,createEntity,merge,nextClock} from '../src/models/entities';
import type {Entity,EntityPatch,Kind} from '../src/models/entities';

// Fault controls wrap the existing repository; all merge and sync behavior is production code.
class Link implements AgendaRepository {
 offline=false; failure:RepositoryError|null=null; lostAck=false;
 gate:Promise<void>|null=null; calls:string[]=[];
 constructor(readonly remote:MemoryRepository){}
 fetch(id:string){return this.remote.fetch(id)}
 async fetchChanges(cursor?:string):Promise<ChangePage>{this.calls.push('pull');if(this.offline)throw new RepositoryError('network');const page=await this.remote.fetchChanges(cursor);await this.gate;return page}
 async save(e:Entity,op:string){this.calls.push('push');if(this.failure){const failure=this.failure;this.failure=null;throw failure}const result=await this.remote.save(e,op);if(this.lostAck){this.lostAck=false;throw new RepositoryError('network')}return result}
}
async function device(writer:string,remote:MemoryRepository){
 const persistence=new MemoryPersistence(),store=new AgendaStore(persistence,writer);
 const auth=new AuthManager({signIn:async()=> 'firebase:M2-user',signOut:async()=>{}});
 await store.boot();await auth.signIn();const link=new Link(remote);
 return {store,persistence,auth,link,engine:new SyncEngine(store,link,auth,()=>0)};
}
const canonical=(entities:Entity[])=>clone(entities).sort((a,b)=>a.id.localeCompare(b.id));
async function harness(){
 const remote=new MemoryRepository(2),mac=await device('Mac',remote),iphone=await device('iPhone',remote);
 async function converge(order=[mac,iphone]){for(let round=0;round<3;round++)for(const d of order)await d.engine.sync();const records=new Map<string,Entity>();let cursor:string|undefined;for(;;){const page=await remote.fetchChanges(cursor);for(const e of page.entities)records.set(e.id,e);if(!page.moreComing)break;cursor=page.cursor}const expected=canonical([...records.values()]);expect(canonical(mac.store.entities)).toEqual(expected);expect(canonical(iphone.store.entities)).toEqual(expected);expect(mac.store.outbox).toEqual([]);expect(iphone.store.outbox).toEqual([]);return expected}
 async function seed(fields:EntityPatch={}){const e=await mac.store.create('Task',fields);await converge();return e.id}
 return {remote,mac,iphone,converge,seed};
}
afterEach(()=>vi.useRealTimers());
describe('M2 independent devices',()=>{
 it('1–3 independent stores, disks, writers, outboxes and bidirectional creates',async()=>{const h=await harness();expect(h.mac.persistence).not.toBe(h.iphone.persistence);expect(h.mac.store).not.toBe(h.iphone.store);expect(h.mac.auth.identity).toBe(h.iphone.auth.identity);const a=await h.mac.store.create('Task',{title:'Mac'}),b=await h.iphone.store.create('Task',{title:'Phone'});expect(a.fieldClocks.title.writerID).toBe('Mac');expect(b.fieldClocks.title.writerID).toBe('iPhone');expect(h.mac.store.outbox[0].operationID).not.toBe(h.iphone.store.outbox[0].operationID);expect(await h.converge()).toHaveLength(2)});
 it('4 lost ACK retries the same operation without duplicate remote changes',async()=>{const h=await harness();await h.mac.store.create('Task');const op=h.mac.store.outbox[0].operationID;h.mac.link.lostAck=true;await h.mac.engine.sync();expect(h.mac.store.outbox[0].operationID).toBe(op);expect(h.mac.store.outbox[0].status).toBe('retry');await h.mac.store.markOperation(op,{nextAttemptAt:0});await h.converge();expect((await h.remote.fetchChanges()).entities).toHaveLength(1)});
 it('5 independent title and priority edits survive',async()=>{const h=await harness(),id=await h.seed();await h.mac.store.patch(id,{title:'Mac'});await h.iphone.store.patch(id,{priority:3});expect((await h.converge())[0].fields).toMatchObject({title:'Mac',priority:3})});
 it('6–8 equal-time conflicts converge in both orders and repeated sync is idempotent',async()=>{
 vi.useFakeTimers();vi.setSystemTime('2026-10-07T10:00:00Z');const h=await harness(),id=await h.seed();await h.mac.store.patch(id,{title:'Mac'});await h.iphone.store.patch(id,{title:'Phone'});const expected=merge(h.mac.store.entities[0],h.iphone.store.entities[0]);
 const snapshotA=h.mac.store.snapshot(),snapshotB=h.iphone.store.snapshot();const first=await h.converge();expect(first[0]).toEqual(expected);
 const other=await harness();await other.mac.persistence.save(snapshotA);await other.iphone.persistence.save(snapshotB);await other.mac.store.boot();await other.iphone.store.boot();expect(await other.converge([other.iphone,other.mac])).toEqual(first);expect(await h.converge()).toEqual(first)
 });
 for(const action of ['complete','delete','restore'] as const)it('9–13 lifecycle '+action+' with independent offline edit',async()=>{const h=await harness(),id=await h.seed();if(action==='restore'){await h.mac.store.patch(id,{},'deleted');await h.converge()}h.iphone.link.offline=true;await h.iphone.engine.sync();await h.iphone.store.patch(id,{notes:'offline'});if(action==='complete')await h.mac.store.complete(id,true);else await h.mac.store.patch(id,{},action==='delete'?'deleted':'active');await h.mac.engine.sync();h.iphone.link.offline=false;const result=(await h.converge())[0];expect(result.fields.notes).toBe('offline');expect(result.lifecycle).toBe(action==='delete'?'deleted':'active');if(action==='complete')expect(result.fields.completed).toBe(true)});
 it('11 delete/restore concurrent lifecycle winner follows clocks',async()=>{const h=await harness(),id=await h.seed();await h.mac.store.patch(id,{},'deleted');await h.converge();await h.mac.store.patch(id,{},'active');await h.iphone.store.patch(id,{},'active');await h.iphone.store.patch(id,{},'deleted');const expected=merge(h.mac.store.entities[0],h.iphone.store.entities[0]);expect((await h.converge())[0]).toEqual(expected)});
 it('14–18 related entities and independent relation edits preserve references',async()=>{const h=await harness(),id=await h.seed();const parent=await h.mac.store.create('Label',{title:'Parent'}),label=await h.mac.store.create('Label',{title:'Child',parentLabelId:parent.id});const child=await h.mac.store.create('Subtask',{parentTaskId:id});await h.converge();await h.mac.store.patch(id,{labelIDs:[label.id]});await h.iphone.store.patch(child.id,{title:'Child edited'});const entities=await h.converge();expect(entities.find(e=>e.id===id)?.fields.labelIDs).toEqual([label.id]);expect(entities.find(e=>e.id===child.id)?.fields.parentTaskId).toBe(id);expect(entities.find(e=>e.id===label.id)?.fields.parentLabelId).toBe(parent.id)});
 const fixtures:[Kind,EntityPatch][]=[['Task',{}],['Subtask',{parentTaskId:'00000000-0000-4000-8000-000000000001'}],['Reminder',{due:'2026-10-07T12:00:00.000Z'}],['Event',{allDay:true,startDate:'2026-10-07',endDate:'2026-10-08'}],['QuickNote',{text:'Note'}],['Label',{title:'Label'}],['Template',{name:'Template',definition:{targetKind:'Task',values:{title:'Default'}}}],['Preferences',{theme:'dark'}]];
 for(const [kind,fields] of fixtures)it('19–26 '+kind+' full entity convergence',async()=>{const h=await harness();if(kind==='Subtask'){const parent=createEntity('Task');parent.id=fields.parentTaskId!;await h.remote.save(parent,'parent');await h.converge()}await h.mac.store.create(kind,fields);await h.converge()});
 it('27–29 moved start and resized duration merge independently',async()=>{const h=await harness(),id=await h.seed({scheduledStartAt:'2026-10-07T08:00:00.000Z',scheduledDurationMinutes:60,scheduledTimezone:'Europe/Madrid'});await h.mac.store.patch(id,{scheduledStartAt:'2026-10-07T09:00:00.000Z'});await h.iphone.store.patch(id,{scheduledDurationMinutes:90});expect((await h.converge())[0].fields).toMatchObject({scheduledStartAt:'2026-10-07T09:00:00.000Z',scheduledDurationMinutes:90})});
 it('31–36 offline queued edits reconnect with pull before push and drain',async()=>{const h=await harness(),id=await h.seed();h.mac.link.offline=true;await h.mac.engine.sync();expect(h.mac.store.status).toBe('offline');await h.mac.store.patch(id,{title:'offline'});await h.mac.store.patch(id,{notes:'queued'});await h.iphone.store.patch(id,{priority:3});await h.iphone.engine.sync();h.mac.link.offline=false;h.mac.link.calls=[];await h.converge();expect(h.mac.link.calls[0]).toBe('pull');expect(h.mac.link.calls.indexOf('push')).toBeGreaterThan(0);expect(h.mac.store.entities[0].fields).toMatchObject({title:'offline',notes:'queued',priority:3})});
 it('41–43 delayed A response cannot mutate B or the detached A store',async()=>{const h=await harness();await h.seed();let release!:()=>void;h.mac.link.gate=new Promise<void>(r=>release=r);const pending=h.mac.engine.sync();await h.mac.auth.signOut();h.mac.store.detach();const b=await device('B',new MemoryRepository());release();await pending;expect(h.mac.store.entities).toEqual([]);expect(b.store.entities).toEqual([])});
 it('44–45 expiration preserves durable operations and same user relogin resumes',async()=>{const h=await harness();await h.mac.store.create('Task');h.mac.link.failure=new RepositoryError('authentication');await h.mac.engine.sync();expect(h.mac.auth.state).toBe('expired');expect((await h.mac.persistence.load()).outbox).toHaveLength(1);await h.mac.auth.signIn();h.mac.engine=new SyncEngine(h.mac.store,h.mac.link,h.mac.auth,()=>0);await h.converge()});
 it('47–48 expired cursor resets once and normal cursor advances',async()=>{const h=await harness();await h.seed();h.iphone.store.cursor='999';const fetch=vi.spyOn(h.remote,'fetchChanges');await h.iphone.engine.sync();expect(fetch.mock.calls).toEqual([['999'],[undefined]]);expect(h.iphone.store.cursor).toBe('1');await h.mac.store.create('Task');await h.converge();expect(h.iphone.store.cursor).toBe('2')});
 it('49 stalled cursor fails in a controlled way',async()=>{const h=await harness();h.mac.store.cursor='0';vi.spyOn(h.mac.link,'fetchChanges').mockResolvedValue({entities:[],cursor:'0',moreComing:true});await h.mac.engine.sync();expect(h.mac.store.status).toBe('offline');expect(h.mac.store.error).toBe('SYNC_FAILED');expect(h.mac.store.outbox).toEqual([])});
 it('50 new empty device reconstructs all kinds, completed, tombstones and scheduling; multiple Preferences remain',async()=>{const h=await harness();for(const [kind,fields] of fixtures){if(kind==='Subtask')continue;await h.mac.store.create(kind,fields)}const parent=await h.mac.store.create('Task');await h.mac.store.create('Subtask',{parentTaskId:parent.id});const completed=await h.mac.store.create('Task');await h.mac.store.complete(completed.id,true);const deleted=await h.mac.store.create('Task');await h.mac.store.patch(deleted.id,{},'deleted');await h.mac.store.create('Task',{scheduledStartAt:'2026-10-07T08:00:00.000Z',scheduledDurationMinutes:60,scheduledTimezone:'Europe/Madrid'});await h.mac.store.create('Preferences',{theme:'light'});await h.mac.engine.sync();expect(h.iphone.store.entities).toEqual([]);await h.converge();expect(h.iphone.store.entities.filter(e=>e.kind==='Preferences')).toHaveLength(2);expect(h.iphone.store.entities.find(e=>e.id===completed.id)?.fields.completed).toBe(true);expect(h.iphone.store.entities.find(e=>e.id===deleted.id)?.lifecycle).toBe('deleted')});
 for(const code of ['network','conflict','permission','invalidRecord'] as const)it('51–54,56–57 '+code+' classification, same entity blocked, other entity continues',async()=>{const h=await harness(),e=await h.mac.store.create('Task');await h.mac.store.patch(e.id,{title:'later'});const other=await h.mac.store.create('QuickNote');h.mac.link.failure=new RepositoryError(code);await h.mac.engine.sync();expect(h.mac.store.outbox[0].status).toBe(['permission','invalidRecord'].includes(code)?'permanentFailure':code==='conflict'?'conflict':'retry');expect(h.mac.store.outbox[1].attempts).toBe(0);expect(await h.remote.fetch(other.id)).not.toBeNull();if(code==='network'||code==='conflict'){await h.mac.store.markOperation(h.mac.store.outbox[0].operationID,{nextAttemptAt:0});await h.converge()}});
 it('58 same UUID different kind is quarantined without replacing original',async()=>{const h=await harness(),id=await h.seed();const collision=createEntity('QuickNote');collision.id=id;await h.mac.store.remote([collision]);expect(h.mac.store.entities[0].kind).toBe('Task');expect(h.mac.store.quarantine.length).toBeGreaterThan(0)});
 it('59–60 future/backward clocks and deterministic merge properties',()=>{const a=createEntity('Task'),b=clone(a);const future=nextClock('Mac',Object.values(a.fieldClocks),Date.now()+100000);a.fieldClocks.title=future;a.fields.title='future';b.fieldClocks.priority=nextClock('iPhone',[future],0);b.fields.priority=3;expect(b.fieldClocks.priority.physicalMilliseconds).toBe(future.physicalMilliseconds);expect(merge(a,b)).toEqual(merge(b,a));expect(merge(a,a)).toEqual(a);expect(merge(a,b)).toEqual(merge(a,b))});
});
