import {expect,it,vi} from 'vitest';
import {AuthManager} from '../src/auth/AuthManager';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence} from '../src/offline/Persistence';
import {MemoryRepository,RepositoryError} from '../src/repositories/AgendaRepository';
import {SyncEngine} from '../src/sync/SyncEngine';

it('M3C authentication during pull expires auth and preserves durable outbox',async()=>{
 const disk=new MemoryPersistence(),store=new AgendaStore(disk);await store.boot();await store.create('Task');
 const auth=new AuthManager({signIn:async()=> 'A',signOut:async()=>{}});await auth.signIn();
 const remote=new MemoryRepository();vi.spyOn(remote,'fetchChanges').mockRejectedValue(new RepositoryError('authentication'));
 await new SyncEngine(store,remote,auth).sync();
 expect(auth.state).toBe('expired');expect((await disk.load()).outbox).toHaveLength(1);
});

import {syncPresentation,lastSyncLabel,synchronizeAgenda} from '../src/sync/syncPresentation';
import {AgendaSession} from '../src/auth/AgendaSession';
import {IndexedDBPersistence} from '../src/offline/Persistence';
import 'fake-indexeddb/auto';

async function fixture(){const disk=new MemoryPersistence(),store=new AgendaStore(disk);await store.boot();const auth=new AuthManager({signIn:async()=> 'A',signOut:async()=>{}});await auth.signIn();const remote=new MemoryRepository(),engine=new SyncEngine(store,remote,auth,()=>0);return {disk,store,auth,remote,engine}}
it.each([
 ['ready',0,null,'ready','Sincronizada'],['syncing',1,null,'syncing','Sincronizando…'],['ready',1,null,'pending','Pendiente'],['pending',1,null,'pending','Pendiente'],['offline',1,'network','offline','Sin conexión'],['offline',0,'network','offline','Sin conexión'],['pending',1,'permission','permanent','Necesita atención'],['pending',1,'invalidRecord','permanent','Necesita atención'],['offline',0,'zoneMissing','permanent','Necesita atención'],['offline',1,'authentication','auth','Necesita atención'],
] as const)('M3C derives %s/%s/%s',async(status,count,cause,state,title)=>{const {store}=await fixture();if(count)await store.create('Task');store.status=status;store.syncIssueCause=cause;expect(syncPresentation(store)).toMatchObject({state,title,pending:count,attention:['permanent','auth'].includes(state)})});
it('M3C local presentation never exposes remote status, pending, lastSync or errors',async()=>{const {store}=await fixture();const local=new AgendaStore(new MemoryPersistence(),undefined,'local-only');local.outbox=store.outbox;local.status='offline';local.syncIssueCause='authentication';local.lastSync='2026-10-07T10:00:00Z';expect(syncPresentation(local)).toEqual({state:'local',title:'Agenda local',detail:'Guardada en este navegador',pending:0,permanent:0,attention:false,lastSync:null})});
it('M3C last sync is optional and deterministically formatted',()=>{expect(lastSyncLabel(null)).toBeNull();expect(lastSyncLabel('invalid')).toBeNull();expect(lastSyncLabel('2026-10-07T10:00:00Z')).toMatch(/^Última sincronización: /)});
it('M3C UI synchronization flushes, refreshes and coalesces concurrent requests',async()=>{const {store,remote,engine}=await fixture();await store.create('Task');store.repository.connectSync(engine);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);const fetch=vi.spyOn(remote,'fetchChanges').mockImplementation(async()=>{await gate;return {entities:[],cursor:'0',moreComing:false}});const first=synchronizeAgenda(store);expect(synchronizeAgenda(store)).toBe(first);release();await first;expect(fetch).toHaveBeenCalledOnce();expect(store.outbox).toEqual([]);expect(syncPresentation(store).state).toBe('ready')});
it('M3C offline/reconnect preserves changes and returns to ready',async()=>{const {store,remote,engine}=await fixture();await store.create('Task');store.repository.connectSync(engine);const pull=vi.spyOn(remote,'fetchChanges').mockRejectedValueOnce(new RepositoryError('network'));await synchronizeAgenda(store);expect(syncPresentation(store).state).toBe('offline');expect(store.outbox).toHaveLength(1);pull.mockRestore();await synchronizeAgenda(store);expect(syncPresentation(store).state).toBe('ready');expect(store.lastSync).not.toBeNull()});
it.each(['permission','invalidRecord','zoneMissing'] as const)('M3C %s failure is counted, persisted and blocks only its entity; retry preserves payload',async code=>{const {store,remote,engine}=await fixture();const first=await store.create('Task');await store.patch(first.id,{title:'later'});const other=await store.create('QuickNote');const original=structuredClone(store.outbox);store.repository.connectSync(engine);const save=vi.spyOn(remote,'save');save.mockRejectedValueOnce(new RepositoryError(code));await synchronizeAgenda(store);expect(store.syncIssueCause).toBe(code);expect(syncPresentation(store)).toMatchObject({state:'permanent',permanent:1,pending:2});expect(store.outbox[1].attempts).toBe(0);expect(await remote.fetch(other.id)).not.toBeNull();await synchronizeAgenda(store);expect(store.outbox).toHaveLength(2);const failed=store.outbox[0];await store.retryPermanentFailures();expect(store.outbox[0]).toEqual({...failed,status:'pending',nextAttemptAt:0});expect(store.outbox.map(op=>op.payload)).toEqual(original.slice(0,2).map(op=>op.payload));await synchronizeAgenda(store);expect(store.outbox).toEqual([]);expect((await remote.fetch(first.id))?.fields.title).toBe('later')});
it('M3C retry write failure rolls back operation metadata and preserves payload',async()=>{const {store,disk}=await fixture();await store.create('Task');await store.markOperation(store.outbox[0].operationID,{status:'permanentFailure',nextAttemptAt:123});const before=store.snapshot();vi.spyOn(disk,'save').mockRejectedValueOnce(Error('disk'));await expect(store.retryPermanentFailures()).rejects.toThrow('disk');expect(store.snapshot()).toEqual(before)});
it('M3C restored permanent failures still require attention without in-memory cause',async()=>{const {store,disk}=await fixture();await store.create('Task');await store.markOperation(store.outbox[0].operationID,{status:'permanentFailure'});const reopened=new AgendaStore(disk);await reopened.boot();expect(syncPresentation(reopened)).toMatchObject({state:'permanent',permanent:1})});
it.each(['pull','push'] as const)('M3C %s auth expiration keeps IndexedDB scope; A resumes and B cannot see or send it',async stage=>{
 let identity='A';const scope='m3c-'+crypto.randomUUID();const auth=new AuthManager({signIn:async()=>identity,signOut:async()=>{}});await auth.signIn();const session=new AgendaSession(auth,id=>new IndexedDBPersistence(scope+id));const remote=new MemoryRepository();await session.attach(remote);const a=session.store!;a.repository.connectSync(null);await a.create('Task',{title:'private A'});const original=a.outbox[0].payload;
 if(stage==='pull')vi.spyOn(remote,'fetchChanges').mockRejectedValueOnce(new RepositoryError('authentication'));else vi.spyOn(remote,'save').mockRejectedValueOnce(new RepositoryError('authentication'));
 await session.sync!.sync();expect(auth.state).toBe('expired');expect(session.store).toBeNull();expect((await new IndexedDBPersistence(scope+'A').load()).outbox[0].payload).toEqual(original);
 identity='B';await auth.signIn();await session.attach(remote);expect(session.store!.entities).toEqual([]);await session.sync!.sync();expect((await remote.fetchChanges()).entities).toEqual([]);
 await session.logout();identity='A';await auth.signIn();await session.attach(remote);expect(session.store!.outbox).toHaveLength(1);await session.sync!.sync();expect(session.store!.outbox).toEqual([]);expect((await remote.fetchChanges()).entities[0].fields.title).toBe('private A');await session.logout();
});
it.each(['pull','push'] as const)('M3C delayed %s A response never modifies B or detached A',async stage=>{let identity='A';const auth=new AuthManager({signIn:async()=>identity,signOut:async()=>{}});await auth.signIn();const disks=new Map<string,MemoryPersistence>();const session=new AgendaSession(auth,id=>{if(!disks.has(id))disks.set(id,new MemoryPersistence());return disks.get(id)!});const remote=new MemoryRepository();await session.attach(remote);const a=session.store!;a.repository.connectSync(null);await a.create('Task');let release!:()=>void;let began!:()=>void;const started=new Promise<void>(r=>began=r),gate=new Promise<void>(r=>release=r);
 if(stage==='pull')vi.spyOn(remote,'fetchChanges').mockImplementationOnce(async()=>{began();await gate;return {entities:[],cursor:'late-A',moreComing:false}});else vi.spyOn(remote,'save').mockImplementationOnce(async e=>{began();await gate;return e});
 const pending=session.sync!.sync();await started;await session.logout();identity='B';await auth.signIn();await session.attach(new MemoryRepository());const b=session.store!,before=b.snapshot();release();await pending;expect(b.snapshot()).toEqual(before);expect(a.entities).toEqual([]);expect((await disks.get('A')!.load()).outbox).toHaveLength(1);await session.logout();
});
it.each(['network','server','rateLimit','conflict','unknown'] as const)('M3C transient %s keeps a typed cause and retries automatically with payload intact',async code=>{const {store,remote,engine}=await fixture();await store.create('Task');const payload=structuredClone(store.outbox[0].payload);vi.spyOn(remote,'save').mockRejectedValueOnce(new RepositoryError(code));await engine.sync();expect(store.syncIssueCause).toBe(code);expect(store.outbox[0].payload).toEqual(payload);expect(store.outbox[0].status).not.toBe('permanentFailure');expect(syncPresentation(store).attention).toBe(false);await store.markOperation(store.outbox[0].operationID,{nextAttemptAt:0});await engine.sync();expect(store.outbox).toEqual([]);expect(store.syncIssueCause).toBeNull();expect(syncPresentation(store).state).toBe('ready')});
it('M3C local refresh never invokes remote synchronization',async()=>{const store=new AgendaStore(new MemoryPersistence(),undefined,'local-only');await store.boot();const sync=vi.fn(async()=>{});store.repository.connectSync({sync});const refresh=vi.spyOn(store,'refresh');await synchronizeAgenda(store);expect(refresh).toHaveBeenCalledOnce();expect(sync).not.toHaveBeenCalled()});
