import 'fake-indexeddb/auto';
import {it,expect,vi} from 'vitest';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence,IndexedDBPersistence} from '../src/offline/Persistence';
import type {Persistence} from '../src/offline/Persistence';
import {clone,schedulingKeys} from '../src/models/entities';
import type {Task} from '../src/models/entities';
import {exportBackup,parseBackup,importBackup} from '../src/backup/backup';
import {encode,decode} from '../src/cloud/CloudGateway';
import {firebaseDocument,firebaseRecord} from '../src/cloud/FirebaseCloudTransport';
const start='2026-10-05T08:00:00.000Z',zone='Europe/Madrid';
const triple={scheduledStartAt:start,scheduledDurationMinutes:60,scheduledTimezone:zone};
async function fixture(p:Persistence=new MemoryPersistence()){const s=new AgendaStore(p);await s.boot();const t=await s.create('Task',{due:'2026-10-06T08:00:00.000Z'});return {s,id:t.id,p}}
const task=(s:AgendaStore)=>s.entities[0] as Task;
async function schedule(s:AgendaStore,id:string){await s.service.scheduleTask(id,start,60,zone)}
it('schedules atomically with one persisted outbox operation and shared clocks',async()=>{const {s,id,p}=await fixture(),save=vi.spyOn(p,'save'),due=task(s).fields.due;await schedule(s,id);expect(task(s).fields).toMatchObject({...triple,due,completed:false,recurrence:null});expect(save).toHaveBeenCalledTimes(1);expect(s.outbox).toHaveLength(2);expect(s.outbox[1].payload).toEqual(task(s));expect(schedulingKeys.map(k=>task(s).fieldClocks[k])).toEqual(Array(3).fill(task(s).fieldClocks.scheduledStartAt));});
it('all scheduling no-ops preserve snapshot, clocks, timestamps and persistence',async()=>{const {s,id,p}=await fixture();await schedule(s,id);const before=clone(s.snapshot()),save=vi.spyOn(p,'save');await schedule(s,id);await s.service.moveScheduledTask(id,start,zone);await s.service.resizeScheduledTask(id,60);expect(s.snapshot()).toEqual(before);expect(save).not.toHaveBeenCalled();});
it('unschedules atomically and modern nulls are a no-op',async()=>{const {s,id,p}=await fixture();await schedule(s,id);const old=clone(task(s)),save=vi.spyOn(p,'save');await s.service.unscheduleTask(id);expect(task(s).fields).toMatchObject({scheduledStartAt:null,scheduledDurationMinutes:null,scheduledTimezone:null,due:old.fields.due});expect(save).toHaveBeenCalledTimes(1);expect(s.outbox).toHaveLength(3);for(const key of schedulingKeys)expect(task(s).fieldClocks[key]).not.toEqual(old.fieldClocks[key]);const before=s.snapshot();save.mockClear();await s.service.unscheduleTask(id);expect(s.snapshot()).toEqual(before);expect(save).not.toHaveBeenCalled();});
it('historical unschedule does not materialize fields or clocks',async()=>{const {s,id,p}=await fixture(),before=s.snapshot(),save=vi.spyOn(p,'save');await s.service.unscheduleTask(id);expect(s.snapshot()).toEqual(before);for(const key of schedulingKeys){expect(Object.hasOwn(task(s).fields,key)).toBe(false);expect(Object.hasOwn(task(s).fieldClocks,key)).toBe(false)}expect(save).not.toHaveBeenCalled();});
it('move and resize change only requested fields and clocks, accepting fractional duration',async()=>{const {s,id}=await fixture();await schedule(s,id);const old=clone(task(s));await s.service.moveScheduledTask(id,'2026-10-05T09:00:00.000Z');expect(task(s).fields).toMatchObject({...triple,scheduledStartAt:'2026-10-05T09:00:00.000Z'});expect(task(s).fieldClocks.scheduledDurationMinutes).toEqual(old.fieldClocks.scheduledDurationMinutes);expect(task(s).fieldClocks.scheduledTimezone).toEqual(old.fieldClocks.scheduledTimezone);await s.service.moveScheduledTask(id,start,'UTC');const moved=clone(task(s));await s.service.resizeScheduledTask(id,22.5);expect(task(s).fields).toMatchObject({...triple,scheduledTimezone:'UTC',scheduledDurationMinutes:22.5});expect(task(s).fieldClocks.scheduledStartAt).toEqual(moved.fieldClocks.scheduledStartAt);expect(task(s).fieldClocks.scheduledTimezone).toEqual(moved.fieldClocks.scheduledTimezone);});
const commands=(s:AgendaStore,id:string)=>[()=>schedule(s,id),()=>s.service.unscheduleTask(id),()=>s.service.moveScheduledTask(id,start),()=>s.service.resizeScheduledTask(id,30)];
it.each(['non-task','deleted','recurring','missing'])('rejects every scheduling command for %s before persistence',async(kind)=>{const {s,id,p}=await fixture();let target=id;if(kind==='non-task')target=(await s.create('QuickNote')).id;if(kind==='deleted')await s.service.delete(id);if(kind==='recurring')await s.patch(id,{recurrence:{frequency:'daily',interval:1,weekdays:[],monthDay:null,until:null,count:null,exceptions:[]}});if(kind==='missing')target=crypto.randomUUID();const before=s.snapshot(),save=vi.spyOn(p,'save');for(const command of commands(s,target))await expect(command()).rejects.toThrow();expect(s.snapshot()).toEqual(before);expect(save).not.toHaveBeenCalled();});
it('move and resize cannot implicitly schedule historical or null tasks',async()=>{const {s,id}=await fixture();for(const run of commands(s,id).slice(2))await expect(run()).rejects.toThrow('TASK_NOT_SCHEDULED');await schedule(s,id);await s.service.unscheduleTask(id);for(const run of commands(s,id).slice(2))await expect(run()).rejects.toThrow('TASK_NOT_SCHEDULED');});
it.each([['bad',60,zone],[start,0,zone],[start,-1,zone],[start,NaN,zone],[start,Infinity,zone],[start,60,'bad-zone'],[start,60,'']])('rejects invalid scheduling triple %s %s %s',async(a,b,c)=>{const {s,id,p}=await fixture(),before=s.snapshot(),save=vi.spyOn(p,'save');await expect(s.service.scheduleTask(id,a as string,b as number,c as string)).rejects.toThrow('INVALID_SCHEDULING');expect(s.snapshot()).toEqual(before);expect(save).not.toHaveBeenCalled();});
it('invalid move/resize fail before persisting',async()=>{const {s,id,p}=await fixture();await schedule(s,id);const before=s.snapshot(),save=vi.spyOn(p,'save');for(const run of [()=>s.service.moveScheduledTask(id,'bad'),()=>s.service.moveScheduledTask(id,start,'bad'),... [0,-1,NaN,Infinity].map(n=>()=>s.service.resizeScheduledTask(id,n))])await expect(run()).rejects.toThrow('INVALID_SCHEDULING');expect(s.snapshot()).toEqual(before);expect(save).not.toHaveBeenCalled();});
it('complete/reopen and delete/restore preserve scheduling and its clocks',async()=>{const {s,id}=await fixture();await schedule(s,id);const clocks=clone(task(s).fieldClocks);for(const run of [()=>s.complete(id,true),()=>s.service.reopen(id),()=>s.service.delete(id),()=>s.service.restore(id)]){await run();expect(task(s).fields).toMatchObject(triple);for(const key of schedulingKeys)expect(task(s).fieldClocks[key]).toEqual(clocks[key])}});
it('undo/redo handles first scheduling, unscheduling and resizing',async()=>{const {s,id}=await fixture();await schedule(s,id);await s.undo();expect(task(s).fields).toMatchObject({scheduledStartAt:null,scheduledDurationMinutes:null,scheduledTimezone:null});await s.redo();expect(task(s).fields).toMatchObject(triple);await s.service.unscheduleTask(id);await s.undo();expect(task(s).fields).toMatchObject(triple);await s.redo();expect(task(s).fields.scheduledStartAt).toBeNull();await s.undo();await s.service.resizeScheduledTask(id,22.5);await s.undo();expect(task(s).fields).toMatchObject(triple);await s.redo();expect(task(s).fields.scheduledDurationMinutes).toBe(22.5);});
it('IndexedDB reload, refresh, integrity and outbox preserve scheduling',async()=>{const p=new IndexedDBPersistence(crypto.randomUUID()),{s,id}=await fixture(p);await schedule(s,id);const next=new AgendaStore(p);await next.boot();expect(next.snapshot()).toEqual(s.snapshot());expect(next.quarantine).toEqual([]);await s.service.unscheduleTask(id);await next.refresh();expect(next.snapshot()).toEqual(s.snapshot());});
it('backup import and cloud/Firebase serialization roundtrip scheduled task unchanged',async()=>{const {s,id}=await fixture();await schedule(s,id);const e=task(s),backup=await parseBackup(JSON.stringify(await exportBackup(s.entities))),next=new AgendaStore(new MemoryPersistence());await next.boot();await importBackup(next,backup,'merge');expect(next.entities).toEqual(s.entities);expect(decode(encode(e))).toEqual(e);expect(decode(firebaseRecord(e.kind+'__'+e.id,firebaseDocument(encode(e),'operation')))).toEqual(e);});
