import {it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {TrashRecovery} from '../src/components/TrashRecovery';
import {AgendaStore} from '../src/stores/AgendaStore';
import {MemoryPersistence} from '../src/offline/Persistence';
import {integrityMessage} from '../src/recovery/integrity';
it('cloud trash offers restore and explains retained tombstones without purge',async()=>{const s=new AgendaStore(new MemoryPersistence());await s.boot();const t=await s.create('Task');await s.service.delete(t.id);render(<TrashRecovery store={s} onMessage={vi.fn()}/>);expect(screen.queryByRole('button',{name:/Purgar/})).toBeNull();expect(screen.getByText(/evitar reapariciones/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Restaurar'})).toBeEnabled()});
it('local trash confirms joint purge with dependency count',async()=>{const s=new AgendaStore(new MemoryPersistence(),'test','local-only');await s.boot();const t=await s.create('Task'),sub=await s.create('Subtask',{parentTaskId:t.id});await s.service.delete(t.id);await s.service.delete(sub.id);render(<TrashRecovery store={s} onMessage={vi.fn()}/>);const confirm=vi.spyOn(window,'confirm').mockReturnValue(true);try{fireEvent.click(screen.getByRole('button',{name:'Purgar conjunto'}));await waitFor(()=>expect(s.entities).toEqual([]));expect(confirm).toHaveBeenCalledWith(expect.stringContaining('2 elementos eliminados'))}finally{confirm.mockRestore()}});
it('integrity summary names recoverable warnings without pending operations',async()=>{const s=new AgendaStore(new MemoryPersistence(),'test','local-only');await s.boot();const label=await s.create('Label');await s.create('Task',{labelIDs:[label.id]});await s.service.delete(label.id);expect(integrityMessage(s.entities,s.quarantine.length)).toContain('1 avisos · 0 datos dañados');expect(integrityMessage(s.entities,0)).toContain('etiquetas eliminadas');expect(integrityMessage(s.entities,0)).not.toContain('pendientes')});
