import {useState} from 'react';
import {Dialog} from '../components/Dialog';
import {parseQuickCapture} from './parser';
import type {QuickCaptureResult} from './types';
import './quick-capture.css';
const copy:Record<string,string>={impossibleDate:'La fecha no es válida.',impossibleTime:'La hora no es válida.',invertedRange:'El intervalo horario no es válido.',ambiguousHour:'Elige una hora.',unknownLabel:'La etiqueta no existe.',ambiguousLabel:'Hay varias etiquetas con ese nombre.',multiplePriorities:'Elige una prioridad.',emptyTitle:'Falta un título.',multipleDates:'Hay varias fechas. Revisa los detalles.',multipleTimes:'Hay varias horas. Revisa los detalles.',invalidContext:'No se pudo interpretar la fecha actual.'};
const kinds={task:'Tarea',reminder:'Recordatorio',event:'Evento',note:'Nota'};
export function QuickCaptureDialog({timezone,labels,onClose,onContinue}:{timezone:string;labels:{id:string;name:string}[];onClose:()=>void;onContinue:(result:QuickCaptureResult)=>void}){
 const [text,setText]=useState(''),[now]=useState(()=>new Date()),[time,setTime]=useState<string|null>(null),[priority,setPriority]=useState<QuickCaptureResult['priority']|undefined>();
 const parsed=parseQuickCapture(text,{now,timezone,locale:'es-ES',labels});
 const issues=parsed.issues.filter(issue=>!(issue==='ambiguousHour'&&time&& !parsed.issues.includes('multipleTimes'))&&!(issue==='multiplePriorities'&&priority!==undefined));
 const result:QuickCaptureResult={...parsed,time:time??parsed.time,priority:priority===undefined?parsed.priority:priority,issues,status:parsed.status==='invalid'?'invalid':issues.length?'needsReview':'exact'};
 return <Dialog initialFocus="input" restoreFocus=".global-search" label="Captura rápida" onClose={onClose}><div className="quick-capture"><header><h2>Captura rápida</h2><button onClick={onClose}>Cerrar</button></header><label>Qué quieres recordar<input placeholder="mañana llamar a Ana" value={text} onChange={e=>{setText(e.target.value);setTime(null);setPriority(undefined)}}/></label>{text.trim()?<><section aria-label="Vista previa" className="capture-preview"><strong>{kinds[result.kind]}</strong><p>{result.title||'Sin título'}</p>{result.kind!=='note'&&<dl>{result.date&&<><dt>Fecha</dt><dd>{result.date}</dd></>}{result.time&&<><dt>Hora</dt><dd>{result.time}{result.endTime?' – '+result.endTime:''}</dd></>}{result.priority&&<><dt>Prioridad</dt><dd>{{alta:'Alta',media:'Media',baja:'Baja'}[result.priority]}</dd></>}{!!result.labelIDs.length&&<><dt>Etiquetas</dt><dd>{result.labelIDs.map(id=>labels.find(l=>l.id===id)?.name).join(', ')}</dd></>}</dl>}</section><div aria-live="polite">{issues.map(issue=><p key={issue}>{copy[issue]??'Revisa los detalles antes de continuar.'}</p>)}</div>{issues.includes('ambiguousHour')&&!issues.includes('multipleTimes')&&<fieldset><legend>Hora</legend>{parsed.candidates.times.map(value=><button key={value} onClick={()=>setTime(value)}>{value}</button>)}</fieldset>}{issues.includes('multiplePriorities')&&<fieldset><legend>Prioridad</legend>{(['alta','media','baja',null] as const).map(value=><button key={value??'none'} onClick={()=>setPriority(value)}>{value?{alta:'Alta',media:'Media',baja:'Baja'}[value]:'Sin prioridad'}</button>)}</fieldset>}<footer><button disabled={result.status==='invalid'} onClick={()=>onContinue(result)}>Editar detalles</button><button className="primary" disabled={result.status!=='exact'} onClick={()=>onContinue(result)}>Crear</button></footer><p className="muted">Continuarás en el editor para revisar y guardar.</p></>:<p className="muted">Escribe una tarea, recordatorio, evento o nota.</p>}</div></Dialog>;
}
