import type {Entity} from '../models/entities';
import {integrity} from '../recovery/integrity';
import {merge,updateEntity,utc} from '../models/entities';
import type {AgendaStore} from '../stores/AgendaStore';
interface BackupBase {schemaVersion:1;createdAt:string;applicationVersion:string;entityCount:number;checksum:string;tasks:Entity[];subtasks:Entity[];reminders:Entity[];events:Entity[];quickNotes:Entity[];labels:Entity[];preferences:Entity[]}
export type Backup = BackupBase & ({format:'MiAgendaBackupV1';formatVersion:1}|{format:'MiAgendaBackupV2';formatVersion:2;templates:Entity[]});
export function backupEntities(b:Backup){return [...b.tasks,...b.subtasks,...b.reminders,...b.events,...b.quickNotes,...b.labels,...b.preferences,...(b.formatVersion===2?b.templates:[])]}
async function checksum(entities:Entity[]){const bytes=new TextEncoder().encode(JSON.stringify(entities));return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(b=>b.toString(16).padStart(2,'0')).join('')}
export async function exportBackup(entities:Entity[]):Promise<Backup & {formatVersion:2}>{if(integrity(entities).issues.length)throw Error('INTEGRITY_FAILED');const data={tasks:entities.filter(e=>e.kind==='Task'),subtasks:entities.filter(e=>e.kind==='Subtask'),reminders:entities.filter(e=>e.kind==='Reminder'),events:entities.filter(e=>e.kind==='Event'),quickNotes:entities.filter(e=>e.kind==='QuickNote'),labels:entities.filter(e=>e.kind==='Label'),preferences:entities.filter(e=>e.kind==='Preferences'),templates:entities.filter(e=>e.kind==='Template')};const grouped=Object.values(data).flat();return {format:'MiAgendaBackupV2',formatVersion:2,schemaVersion:1,createdAt:new Date().toISOString(),applicationVersion:'0.3.0',entityCount:entities.length,checksum:await checksum(grouped),...structuredClone(data)}}
export async function parseBackup(text:string):Promise<Backup>{if(text.length>20000000)throw Error('BACKUP_TOO_LARGE');const b=JSON.parse(text) as Backup;if(!b||!((b.format==='MiAgendaBackupV1'&&b.formatVersion===1)||(b.format==='MiAgendaBackupV2'&&b.formatVersion===2))||b.schemaVersion!==1||!utc(b.createdAt)||typeof b.applicationVersion!=='string')throw Error('INVALID_BACKUP');const groups=[b.tasks,b.subtasks,b.reminders,b.events,b.quickNotes,b.labels,b.preferences,...(b.formatVersion===2?[b.templates]:[])];const kinds=['Task','Subtask','Reminder','Event','QuickNote','Label','Preferences',...(b.formatVersion===2?['Template']:[])];if(groups.some((g,i)=>!Array.isArray(g)||g.some(e=>e?.kind!==kinds[i])))throw Error('INVALID_BACKUP');const entities=backupEntities(b);if(b.entityCount!==entities.length)throw Error('INVALID_BACKUP');/* Hash the original V1/V2 groups before validation or normalization. */if(await checksum(entities)!==b.checksum)throw Error('CHECKSUM_FAILED');if(integrity(entities).issues.length)throw Error('INTEGRITY_FAILED');return b}
export async function importBackup(store:AgendaStore,backup:Backup,mode:'merge'|'replace',confirmation=''){await parseBackup(JSON.stringify(backup));if(mode==='replace'&&confirmation!=='REEMPLAZAR')throw Error('CONFIRMATION_REQUIRED');const previous=await exportBackup(store.entities);const ids=new Set(backupEntities(backup).map(e=>e.id));const changes=backupEntities(backup).map(e=>{const old=store.entities.find(v=>v.id===e.id);if(old&&old.kind!==e.kind)throw Error('IDENTITY_CONFLICT');return old?(mode==='merge'?merge(old,e):updateEntity(old,e.fields,store.writerID,e.lifecycle)):e});if(mode==='replace')changes.push(...store.entities.filter(e=>!ids.has(e.id)).map(e=>updateEntity(e,{},store.writerID,'deleted')));await store.commit(changes);return previous}
export function downloadBackup(backup:Backup){const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='mi-agenda-backup-'+backup.createdAt.slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function previewImport(existing:Entity[],backup:Backup,mode:'merge'|'replace') {const incoming=backupEntities(backup),ids=new Set(incoming.map(e=>e.id)),known=new Set(existing.map(e=>e.id));return {create:incoming.filter(e=>!known.has(e.id)).length,update:incoming.filter(e=>known.has(e.id)).length,delete:mode==='replace'?existing.filter(e=>!ids.has(e.id)&&e.lifecycle==='active').length:0}}
