import type {Entity} from '../models/entities';
export interface OutboxOperation {operationID:string;entityID:string;entityKind:Entity['kind'];operationKind:'save';createdAt:string;writerID:string;baseVersion:string|null;payload:Entity;attempts:number;nextAttemptAt:number;status:'pending'|'sending'|'retry'|'conflict'|'applied'|'permanentFailure'}
export interface Snapshot {entities:Entity[];outbox:OutboxOperation[];cursor?:string;quarantine:{code:string;entity:unknown}[]}
export interface Persistence {load():Promise<Snapshot>;save(snapshot:Snapshot,valid?:()=>boolean):Promise<void>;clear():Promise<void>}
export class MemoryPersistence implements Persistence {private data:Snapshot={entities:[],outbox:[],quarantine:[]};async load(){return structuredClone(this.data)}async save(s:Snapshot,valid=()=>true){if(!valid())throw Error('STALE_SESSION');this.data=structuredClone(s)}async clear(){this.data={entities:[],outbox:[],quarantine:[]}}}
export class IndexedDBPersistence implements Persistence {
 private db:Promise<IDBDatabase>;private revision=0;
 constructor(private identity:string){this.db=new Promise((resolve,reject)=>{const request=indexedDB.open('miagenda',1);request.onupgradeneeded=()=>{for(const name of ['entities','outbox','syncMetadata','preferences','quarantine'])request.result.createObjectStore(name)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('STORAGE_OPEN_FAILED'))})}
 async load():Promise<Snapshot>{const db=await this.db;return new Promise((resolve,reject)=>{const tx=db.transaction(['entities','outbox','syncMetadata','quarantine'],'readonly');const e=tx.objectStore('entities').get(this.identity),o=tx.objectStore('outbox').get(this.identity),m=tx.objectStore('syncMetadata').get(this.identity),q=tx.objectStore('quarantine').get(this.identity);tx.oncomplete=()=>{this.revision=m.result?.revision??0;resolve({entities:e.result??[],outbox:o.result??[],quarantine:q.result??[],cursor:m.result?.cursor})};tx.onerror=()=>reject(Error('STORAGE_READ_FAILED'))})}
 async save(s:Snapshot,valid=()=>true){const db=await this.db;if(!valid())throw Error('STALE_SESSION');return new Promise<void>((resolve,reject)=>{const tx=db.transaction(['entities','outbox','syncMetadata','preferences','quarantine'],'readwrite');const metadata=tx.objectStore('syncMetadata');const request=metadata.get(this.identity);let next=this.revision+1;let stale=false;let staleSession=false;request.onsuccess=()=>{if(!valid()){staleSession=true;tx.abort();return}if((request.result?.revision??0)!==this.revision){stale=true;tx.abort();return}next=this.revision+1;tx.objectStore('entities').put(s.entities,this.identity).addEventListener('success',guard);tx.objectStore('outbox').put(s.outbox,this.identity).addEventListener('success',guard);metadata.put({cursor:s.cursor,revision:next},this.identity).addEventListener('success',guard);tx.objectStore('quarantine').put(s.quarantine,this.identity).addEventListener('success',guard);tx.objectStore('preferences').put(s.entities.filter(e=>e.kind==='Preferences'),this.identity).addEventListener('success',guard)};const guard=()=>{if(!valid()){staleSession=true;tx.abort()}};tx.oncomplete=()=>{this.revision=next;resolve()};tx.onerror=()=>reject(Error('STORAGE_WRITE_FAILED'));tx.onabort=()=>reject(Error(staleSession?'STALE_SESSION':stale?'STORAGE_WRITE_ABORTED_OR_ANOTHER_TAB':'STORAGE_WRITE_FAILED'))})}
 async clear(){await this.save({entities:[],outbox:[],quarantine:[]})}
}
