import {LocalAgendaRepository} from '../repositories/LocalAgendaRepository';
import {AgendaService} from '../services/AgendaService';
import type {Filter} from '../search/selectors';
import {compare,clone,merge,updateEntity,validate,schedulingKeys,entityLabelIDs} from '../models/entities';
import type {Entity,Kind,EntityPatch} from '../models/entities';
import type {OutboxOperation,Persistence,Snapshot} from '../offline/Persistence';
import {integrity} from '../recovery/integrity';
export class AgendaStore {
 entities:Entity[]=[];outbox:OutboxOperation[]=[];cursor:string|undefined;quarantine:Snapshot['quarantine']=[];status='booting';error='';revision=0;lastSync:string|null=null;filters:Filter={};selection:string[]=[];
 get syncStatus(){return this.status} get pendingOperations(){return this.outbox.length} get errors(){return this.error?[this.error]:[]}
 setFilters(filters:Filter){this.filters=filters;this.emit()} setSelection(ids:string[]){this.selection=[...new Set(ids)];this.emit()}
 private listeners=new Set<()=>void>();private tail:Promise<void>=Promise.resolve();private epoch=0;private undoStack:{before:Entity[];after:Entity[];keys?:Record<string,(keyof EntityPatch)[]>}[]=[];private redoStack:{before:Entity[];after:Entity[];keys?:Record<string,(keyof EntityPatch)[]>}[]=[];
 constructor(public persistence:Persistence,public writerID:string=crypto.randomUUID()){}
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return ()=>{this.listeners.delete(fn)}};
 getSnapshot=()=>this.revision;
 emit(){this.revision++;this.listeners.forEach(fn=>fn())}
 snapshot():Snapshot{return clone({entities:this.entities,outbox:this.outbox,cursor:this.cursor,quarantine:this.quarantine})}
 async boot(){this.status='booting';const epoch=this.epoch;try{const s=await this.persistence.load();if(epoch!==this.epoch)return;const checked=integrity(s.entities);this.entities=checked.entities;this.quarantine=[...s.quarantine,...checked.quarantine];const seen=new Set<string>();this.outbox=s.outbox.filter(o=>{try{if(seen.has(o.operationID))return false;seen.add(o.operationID);validate(o.payload);if(o.entityID!==o.payload.id||!o.operationID)throw Error();return true}catch{this.quarantine.push({code:'INVALID_OUTBOX',entity:o});return false}}).map(o=>({...o,status:o.status==='sending'?'retry':o.status}));this.cursor=s.cursor;this.status='ready'}catch{if(epoch!==this.epoch)return;this.status='safe';this.error='STORAGE_OPEN_FAILED'}this.emit()}
 detach(){this.epoch++;this.entities=[];this.outbox=[];this.cursor=undefined;this.quarantine=[];this.undoStack=[];this.redoStack=[];this.filters={};this.selection=[];this.error='';this.lastSync=null;this.status='signedOut';this.emit()}
 private queue<T>(fn:()=>Promise<T>):Promise<T>{const next=this.tail.then(fn);this.tail=next.then(()=>{},()=>{});return next}
 async flush(){await this.tail}
 private async persist(snapshot:Snapshot,base:Snapshot,epoch:number):Promise<Snapshot>{for(let attempt=0;attempt<5;attempt++){try{if(epoch!==this.epoch)throw Error('STALE_SESSION');await this.persistence.save(snapshot,()=>epoch===this.epoch);return snapshot}catch(error){if(!(error instanceof Error)||error.message!=='STORAGE_WRITE_ABORTED_OR_ANOTHER_TAB')throw error;const disk=await this.persistence.load();const map=new Map(disk.entities.map(e=>[e.id,e]));for(const entity of snapshot.entities){const old=map.get(entity.id);if(old)map.set(entity.id,merge(old,entity));else if(!base.entities.some(e=>e.id===entity.id))map.set(entity.id,entity)}const desired=new Map(snapshot.outbox.map(o=>[o.operationID,o])),prior=new Set(base.outbox.map(o=>o.operationID));const operations=disk.outbox.filter(o=>!prior.has(o.operationID)||desired.has(o.operationID)).map(o=>desired.get(o.operationID)??o);const seen=new Set(operations.map(o=>o.operationID));for(const op of desired.values())if(!prior.has(op.operationID)&&!seen.has(op.operationID)){operations.push(op);seen.add(op.operationID)}snapshot={entities:[...map.values()],outbox:operations,cursor:disk.cursor!==base.cursor?disk.cursor:snapshot.cursor,quarantine:[...disk.quarantine,...snapshot.quarantine.filter(q=>!base.quarantine.some(b=>JSON.stringify(b)===JSON.stringify(q)))]};base=disk}}throw Error('STORAGE_BUSY')}
 async refresh(){const epoch=this.epoch;await this.queue(async()=>{const disk=await this.persistence.load();if(epoch!==this.epoch||this.status==='signedOut')return;const checked=integrity(disk.entities);this.entities=checked.entities;this.outbox=disk.outbox;this.cursor=disk.cursor;this.quarantine=[...disk.quarantine,...checked.quarantine];this.emit()})}

 private operation(entity:Entity):OutboxOperation{return {operationID:crypto.randomUUID(),entityID:entity.id,entityKind:entity.kind,operationKind:'save',createdAt:new Date().toISOString(),writerID:this.writerID,baseVersion:null,payload:clone(entity),attempts:0,nextAttemptAt:0,status:'pending'}}
 commit(input:Entity[]|(()=>Entity[]),history=true):Promise<void>{const epoch=this.epoch;return this.queue(async()=>{if(epoch!==this.epoch)throw Error('STALE_SESSION');if(['safe','signedOut','booting'].includes(this.status))throw Error('READ_ONLY');let changes=clone(typeof input==='function'?input():input);changes.forEach(validate);changes=changes.filter(change=>!this.entities.some(entity=>entity.id===change.id&&JSON.stringify(entity)===JSON.stringify(change)));if(!changes.length)return;const prior=this.snapshot();const before=changes.flatMap(c=>this.entities.filter(e=>e.id===c.id));const ids=new Set(changes.map(e=>e.id));const candidate=[...this.entities.filter(e=>!ids.has(e.id)),...changes];if(integrity(candidate).issues.some(i=>i.code==='LABEL_CYCLE'||i.code==='ORPHAN_PARENT'))throw Error('INVALID_RELATION');this.entities=candidate;this.outbox.push(...changes.map(e=>this.operation(e)));this.emit();try{const saved=await this.persist(this.snapshot(),prior,epoch);if(epoch!==this.epoch)return;this.entities=saved.entities;this.outbox=saved.outbox;this.cursor=saved.cursor;this.quarantine=saved.quarantine;if(history){this.undoStack.push({before:clone(before),after:clone(changes)});this.redoStack=[]}this.error=''}catch{if(epoch===this.epoch){this.entities=prior.entities;this.outbox=prior.outbox;this.error='STORAGE_WRITE_FAILED'}throw Error('STORAGE_WRITE_FAILED')}finally{if(epoch===this.epoch)this.emit()}})}
 readonly repository=new LocalAgendaRepository(()=>this.entities,()=>this.writerID,changes=>this.commit(changes),()=>this.flush());
 readonly service=new AgendaService(this.repository);
 create(kind:Kind,fields:EntityPatch={}){return this.service.create(kind,fields)}
 patch(id:string,fields:EntityPatch,lifecycle?:Entity['lifecycle']){return this.service.patch(id,fields,lifecycle)}
 bulk(ids:string[],fields:EntityPatch,lifecycle?:Entity['lifecycle']){return this.service.bulk(ids,fields,lifecycle)}
 complete(id:string,completed:boolean){return this.service.complete(id,completed)}
 duplicate(id:string){return this.service.duplicate(id)}
 async undo(){await this.flush();const entry=this.undoStack.pop();if(!entry)return;try{await this.commit(entry.after.map(e=>{const now=this.entities.find(x=>x.id===e.id)??e,before=entry.before.find(x=>x.id===e.id);const patch:EntityPatch={};if(before)for(const key of Object.keys(e.fields) as (keyof EntityPatch)[])if((!before.fieldClocks[key]||compare(before.fieldClocks[key],e.fieldClocks[key])!==0)&&compare(now.fieldClocks[key],e.fieldClocks[key])===0)Object.assign(patch,{[key]:(before.fields as EntityPatch)[key]??(schedulingKeys.includes(key as typeof schedulingKeys[number])?null:(before.fields as EntityPatch)[key])});const lifecycle=compare(now.fieldClocks.lifecycle,e.fieldClocks.lifecycle)===0?before?.lifecycle??'deleted':now.lifecycle;return updateEntity(now,patch,this.writerID,lifecycle)}),false);this.redoStack.push({...entry,keys:Object.fromEntries(entry.after.map(e=>{const before=entry.before.find(b=>b.id===e.id);return [e.id,before?(Object.keys(e.fields) as (keyof EntityPatch)[]).filter(k=>(!before.fieldClocks[k]||compare(before.fieldClocks[k],e.fieldClocks[k])!==0)):[]]})),before:clone(this.entities.filter(e=>entry.after.some(a=>a.id===e.id)))})}catch(e){this.undoStack.push(entry);throw e}}
 async redo(){await this.flush();const entry=this.redoStack.pop();if(!entry)return;try{await this.commit(entry.after.map(e=>{const now=this.entities.find(x=>x.id===e.id)??e,before=entry.before.find(b=>b.id===e.id);const patch:EntityPatch={};if(before)for(const key of Object.keys(e.fields) as (keyof EntityPatch)[])if(entry.keys?.[e.id]?.includes(key)&&compare(now.fieldClocks[key],before.fieldClocks[key])===0)Object.assign(patch,{[key]:(e.fields as EntityPatch)[key]});return updateEntity(now,patch,this.writerID,before&&compare(now.fieldClocks.lifecycle,before.fieldClocks.lifecycle)===0?e.lifecycle:now.lifecycle)}),false);this.undoStack.push({...entry,after:clone(this.entities.filter(e=>entry.after.some(a=>a.id===e.id)))})}catch(e){this.redoStack.push({...entry,before:clone(this.entities.filter(e=>entry.after.some(a=>a.id===e.id)))});throw e}}
 async remote(entities:Entity[],cursor?:string,appliedOperation?:string,quarantine:unknown[]=[]){const epoch=this.epoch;await this.queue(async()=>{if(epoch!==this.epoch)throw Error('STALE_SESSION');let snapshot=this.snapshot();const base=clone(snapshot),map=new Map(snapshot.entities.map(e=>[e.id,e]));for(const e of entities){try{validate(e);const local=map.get(e.id);map.set(e.id,local?merge(local,e):e)}catch{snapshot.quarantine.push({code:'REMOTE_INVALID',entity:e})}}snapshot.quarantine.push(...quarantine.map(entity=>({code:'REMOTE_INVALID',entity})));snapshot.entities=[...map.values()];snapshot.cursor=cursor??snapshot.cursor;if(appliedOperation)snapshot.outbox=snapshot.outbox.filter(o=>o.operationID!==appliedOperation);snapshot=await this.persist(snapshot,base,epoch);if(epoch!==this.epoch)return;this.entities=snapshot.entities;this.outbox=snapshot.outbox;this.cursor=snapshot.cursor;this.quarantine=snapshot.quarantine;this.emit()})}
 async purge(ids:string[],confirmation:string){if(confirmation!=='PURGAR')throw Error('CONFIRMATION_REQUIRED');const epoch=this.epoch;await this.queue(async()=>{if(epoch!==this.epoch||this.status==='signedOut'||this.status==='safe')throw Error('READ_ONLY');const removed=new Set(ids);for(const id of ids){const e=this.entities.find(e=>e.id===id);if(!e||e.lifecycle!=='deleted'||this.outbox.some(o=>o.entityID===id))throw Error('PURGE_NOT_ACKNOWLEDGED');if(this.entities.some(e=>!removed.has(e.id)&&((e.kind!=='Template'&&(e.fields.parentTaskId===id||e.fields.parentLabelId===id))||entityLabelIDs(e).includes(id))))throw Error('PURGE_REFERENCED')}const snapshot=this.snapshot();snapshot.entities=snapshot.entities.filter(e=>!removed.has(e.id));await this.persistence.save(snapshot,()=>epoch===this.epoch);if(epoch!==this.epoch)return;this.entities=snapshot.entities;this.undoStack=[];this.redoStack=[];this.emit()})}
 async markOperation(id:string,patch:Partial<OutboxOperation>){const epoch=this.epoch;await this.queue(async()=>{if(epoch!==this.epoch)throw Error('STALE_SESSION');let s=this.snapshot();const base=clone(s);s.outbox=s.outbox.map(o=>o.operationID===id?{...o,...patch}:o);s=await this.persist(s,base,epoch);if(epoch!==this.epoch)return;this.entities=s.entities;this.outbox=s.outbox;this.cursor=s.cursor;this.quarantine=s.quarantine;this.emit()})}
}
