import {useState} from 'react';
import type {ReactNode} from 'react';
import type {AgendaEntity as Entity,Fields} from '../models/entities';
import {addDays,coversDate,occurrences,wallTime} from '../utils/calendar';
import {select} from '../search/selectors';
import {Icon} from './Icon';
import {selectRadar} from '../radar/selectRadar';
import type {IconName} from './Icon';
type Kind=Entity['kind'];
type Destination='Tareas'|'Recordatorios'|'Calendario'|'Notas';
export function Dashboard({entities,today,prefs,onOpen,onCreate,onNavigate,renderList,onMessage}:{entities:Entity[];today:string;prefs:Fields;onOpen:(e:Entity)=>void;onCreate:(kind:Kind)=>void;onNavigate:(section:Destination)=>void;renderList:(items:Entity[])=>ReactNode;onMessage:(message:string)=>void}){
 const [mode,setMode]=useState<'Semana'|'Mes'>('Semana'),[selected,setSelected]=useState(today);
 const radar=selectRadar(entities,new Date().toISOString(),prefs.timezone);
 const tomorrow=addDays(today,1),tasks=select(entities,{kind:'Task',completed:false}).filter(e=>!e.fields.due),reminders=select(entities,{kind:'Reminder',completed:false}).sort((a,b)=>(a.fields.due??'').localeCompare(b.fields.due??''));
 const first=mode==='Semana'?addDays(today,-((new Date(today+'T12:00:00Z').getUTCDay()-prefs.weekStart+7)%7)):today.slice(0,7)+'-01';
 const start=mode==='Semana'?first:addDays(first,-((new Date(first+'T12:00:00Z').getUTCDay()-prefs.weekStart+7)%7));
 const days=Array.from({length:mode==='Semana'?7:42},(_,i)=>addDays(start,i));
 const all=entities.filter(e=>['Event','Task','Reminder'].includes(e.kind)&&!e.fields.completed).flatMap(e=>occurrences(e,addDays(days[0],-366),addDays(days.at(-1)!,2)));
 const onDay=(day:string)=>all.filter(o=>coversDate(o,day,prefs.timezone));
 function summary(day:string){const items=onDay(day);return <div className={'summary-day '+(day===today?'summary-today':'summary-tomorrow')}><strong>{day===today?'Hoy':'Mañana'}</strong><small>{items.length} elemento(s)</small>{items.length?items.slice(0,4).map(o=><button key={o.key} className={'summary-entry tone-'+o.entity.kind} onClick={()=>onOpen(o.entity)}><strong>{o.entity.fields.title}</strong><small>{o.entity.fields.allDay?'Todo el día':o.start?wallTime(o.start,prefs.timezone).slice(11,16):''}</small></button>):<p className="nothing"><Icon name="check"/> Nada programado</p>}</div>}
 function cardHeader(title:string,subtitle:string,icon:IconName){return <header className="card-heading"><span className="section-glyph"><Icon name={icon}/></span><div><h3>{title}</h3><small>{subtitle}</small></div></header>}
 function footer(destination:Destination,kind:'Task'|'Reminder'|'Event'|'QuickNote',label:string){return <footer className="card-footer"><button className="quiet" onClick={()=>onNavigate(destination)}><Icon name="arrow"/>{label}</button><button className="quiet add-small" aria-label={'Crear '+({Task:'tarea',Reminder:'recordatorio',Event:'evento',QuickNote:'nota'}[kind])} onClick={()=>onCreate(kind)}><Icon name="plus"/></button></footer>}
 async function copy(){try{await navigator.clipboard.writeText(['Hoy',...onDay(today).map(o=>o.entity.fields.title),'Mañana',...onDay(tomorrow).map(o=>o.entity.fields.title)].join('\n'));onMessage('Resumen copiado.')}catch{onMessage('No se pudo copiar el resumen. Revisa el permiso del portapapeles.')}}
 return <div className="dashboard">
 <section className="card dashboard-card radar-card" aria-label="Radar">{cardHeader('Radar','Vencimientos y solapes','calendar')}<details><summary>{radar.counts.overdue||radar.counts.conflicts?`${radar.counts.overdue} vencidos · ${radar.counts.conflicts} conflictos`:'Sin pendientes urgentes'}</summary><h4>Vencidos</h4>{radar.overdueItems.length?radar.overdueItems.map(e=><button className="summary-entry" key={e.id} onClick={()=>onOpen(e)}>{e.fields.title}</button>):<p className="nothing">Sin vencidos</p>}<h4>Conflictos</h4>{radar.conflicts.length?radar.conflicts.map(c=><div key={c.key}><small>{wallTime(c.start,prefs.timezone).replace('T',' ')} – {wallTime(c.end,prefs.timezone).replace('T',' ')}</small><button className="summary-entry" onClick={()=>onOpen(c.first.entity)}>{c.first.entity.fields.title}</button><button className="summary-entry" onClick={()=>onOpen(c.second.entity)}>{c.second.entity.fields.title}</button></div>):<p className="nothing">Sin conflictos</p>}</details></section>
 <section className="card dashboard-card tone-today">{cardHeader('Hoy','Tu agenda inmediata','sun')}{summary(today)}<div className="card-divider"/>{summary(tomorrow)}<div className="undated"><Icon name="tasks"/>{tasks.length} tareas sin fecha</div><footer className="card-footer"><button className="quiet" onClick={()=>onMessage(onDay(today).length?onDay(today).map(o=>o.entity.fields.title).join(' · '):'Hoy no tienes nada programado.')}><Icon name="sparkles"/>Resumen de hoy</button><button className="quiet secondary" onClick={()=>void copy()}><Icon name="copy"/>Copiar resumen</button></footer></section>
 <section className="card dashboard-card tone-Event">{cardHeader('Calendario','Semana y próximos eventos','calendar')}<div className="mini-controls"><span>Vista</span><div className="segmented" aria-label="Vista del calendario del dashboard">{(['Semana','Mes'] as const).map(v=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(v)}>{v}</button>)}</div><button className="quiet" onClick={()=>onNavigate('Calendario')}>Ampliar</button></div><div className="mini-calendar">{days.map((day,i)=><button key={day} className={(day===selected?'selected ':'')+(day===today?'is-today':'')} aria-label={day} aria-pressed={day===selected} onClick={()=>setSelected(day)}>{(mode==='Semana'||i<7)&&<small>{new Intl.DateTimeFormat('es',{weekday:'narrow',timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'))}</small>}<strong>{Number(day.slice(8))}</strong><span className={onDay(day).length?'event-dot':'no-dot'}/></button>)}</div><div className="mini-agenda"><header><strong>{new Intl.DateTimeFormat('es',{weekday:'long',day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(selected+'T12:00:00Z'))}</strong><small>{onDay(selected).length}</small></header>{onDay(selected).length?onDay(selected).slice(0,3).map(o=><button key={o.key} className={'mini-event tone-'+o.entity.kind} onClick={()=>onOpen(o.entity)}><Icon name={o.entity.kind==='Event'?'calendar':o.entity.kind==='Task'?'tasks':'reminders'}/>{o.entity.fields.title}</button>):<p className="nothing">Nada programado</p>}</div>{footer('Calendario','Event','Ver calendario')}</section>
 <section className="card dashboard-card tone-Task">{cardHeader('Tareas',`${tasks.length} pendientes sin fecha`,'tasks')}<div className="dashboard-list">{tasks.length?renderList(tasks.slice(0,2)):<div className="empty-mini"><Icon name="check"/><strong>Todo despejado</strong><button className="quiet" onClick={()=>onCreate('Task')}>Nueva tarea</button></div>}</div>{footer('Tareas','Task','Ver todas')}</section>
 <section className="card dashboard-card tone-Reminder">{cardHeader('Recordatorios',`${reminders.length} próximos`,'reminders')}<div className="dashboard-list">{reminders.length?renderList(reminders.slice(0,2)):<div className="empty-mini"><Icon name="check"/><strong>Sin recordatorios pendientes</strong><button className="quiet" onClick={()=>onCreate('Reminder')}>Nuevo recordatorio</button></div>}</div>{footer('Recordatorios','Reminder','Ver todos')}</section>
 <section className="card dashboard-card tone-QuickNote">{cardHeader('Notas rápidas','Tus ideas a mano','notes')}{renderList(select(entities,{kind:'QuickNote',pinned:true}).slice(0,3))}{footer('Notas','QuickNote','Ver notas')}</section>
 </div>
}
