import {readdir,readFile,writeFile} from 'node:fs/promises';
import {generateWorker} from './service-worker.ts';
import {shellVersion} from './shell-version.ts';
const assets=(await readdir('dist/assets')).sort().map(n=>'./assets/'+n);
const manifest=JSON.parse(await readFile('dist/manifest.webmanifest','utf8'));
const icons=[...new Set([...manifest.icons.map(icon=>'./'+icon.src),'./icons/agenda-native-180.png'])];
const shell=['./','./index.html','./manifest.webmanifest',...icons,...assets];
const files=await Promise.all(shell.filter(path=>path!=='./').map(path=>readFile('dist/'+path.slice(2))));
const version=shellVersion(files,generateWorker([],''));
await writeFile('dist/service-worker.js',generateWorker(shell,version));
